
version: 2

models:
  - name: abs_medications
    description: Combines select fields from gold pharmacy tables for all partners
    tests:
      - dbt_utils.expression_is_true:
          expression: "date_add(dateFilled, interval daysSupply - 1 day) = fillEnd"
    columns:
      - name: id
        tests:
          - unique
          - not_null
      - name: memberIdentifier
        description: Coalesces patientId, commonId, and partnerMemberId
      - name: memberIdentifierField
        tests:
          - accepted_values:
              values: ['patientId','commonId','partnerMemberId']
      - name: pharmacyNpi
      - name: prescriberNpi
      - name: partnerPrescriptionNumber
      - name: ndc
        description: National Drug Code
      - name: quantityDispensed
      - name: daysSupply
      - name: ingredient
      - name: memberPaidAmount
        description: Sum of copay, deductible, and coinsurance
        tests:
          - not_null
      - name: planPaidAmount
      - name: dateFilled
      - name: fillEnd
        description: Derived from dateFilled and daysSupply
      - name: partnerName
        description: Indicates gold table of origin
