#!/bin/bash
# script for downloading secret from appropriate GCS bucket and decrypting secret using GCP Cloud KMS.
# Args: ring_name, key_name, path/to/save/secret/ (filename must be the object name in gcs without extension ``.64.enc`)
# Returns: decrypted secret stored on local machine

if [ $# -eq 4 ]; then
  path=$3
  filename=$4
else
  path=$(dirname $3)
  filename=$(basename $3)
fi

gsutil cp gs://$1-secrets/$2/$filename.64.enc - \
| base64 --decode \
| gcloud kms decrypt --location=us \
--project=cbh-kms \
--keyring=$1 \
--key=$2 \
--plaintext-file=$path/$filename \
--ciphertext-file=- \
&& echo Decrypted $filename in $path/$filename
