steps:
  # Generate requirements.txt from Pipfile then delete Pipfile/Pipfile.lock
  # b/c app engine standard doesn't want those files present.
  # https://cloud.google.com/appengine/docs/standard/python3/runtime#dependencies
  - name: "python:3.7-slim"
    id: make-requirements-txt
    entrypoint: "/bin/bash"
    dir: "services/data_docs"
    args:
      - '-c'
      - |
        pip install pipenv \
        && pipenv lock --requirements > ./requirements.txt \
        && rm -f Pipfile*
    waitFor: ['-']
  - name: 'gcr.io/cloud-builders/gcloud'
    id: deploy-data-docs
    dir: "services/data_docs"
    args: [
      "app",
      "deploy",
      "--project", "cityblock-analytics"
    ]
    waitFor:
      - make-requirements-txt

logsBucket: gs://cbh-cloud-build-logs/data_docs
