
version: 2

models:
  - name: mrt_care_pathway_assignment
    description: "\n
    Author:  Katie Claiborne\n
    Purpose: Assign members to care pathways based on partner hierarchy\n
    "
    tests:
      - unique:
          column_name: "concat(patientId, memberPathwayRank)"
    columns:
      - name: id
      - name: patientId
        tests:
          - not_null

      - name: pathwaySlug
        tests:
          - not_null

      - name: memberPathwayRank
        tests:
          - not_null

  - name: mrt_care_pathway_dismissals
    description: Lists input field(s) and evaluated identifiers triggering dismissed suggestions
    tests:
      - dbt_utils.expression_is_true:
          expression: isCurrentSuggestion
          condition: level1Input is not null
    columns:
      - name: id
        description: Unique identifier based on `dismissalId`, `finalInput`, `level1Input`, and `evaluatedResourceId`
        tests:
          - unique
          - not_null
      - name: dismissalId
        description: Commons event identifier, joining to `abs_care_pathway_dismissals`
      - name: isCurrentSuggestion
        description: >
          Indicates whether dismissed suggestion pathway was suggested for member in most recent algorithm run.
        tests:
          - not_null
          - accepted_values:
              values: [true, false]
              quote: false
      - name: pathwaySlug
        tests:
          - not_null
      - name: level1Input
        description: Component field triggering pathway suggestion
      - name: level2Input
        description: Component field triggering `level1Input`
      - name: level3Input
        description: Component field triggering `level2Input`
      - name: level4Input
        description: Component field triggering `level3Input`
      - name: finalInput
        description: >
          Final component triggering dismissed suggestion.
          These fields are based on source data, rather than other computed fields.
      - name: evaluatedResourceId
        description: >
          Identifier joining to source table; use `evaluatedResourceKey` and `evaluatedResourceModel` for guidance
      - name: evaluatedResourceKey
        description: Within `evaluatedResourceModel`, column in which `evaluatedResourceId` will be found
      - name: evaluatedResourceModel
        description: Model in which `evaluatedResourceId` will be found, within column listed in `evaluatedResourceKey`

  - name: mrt_care_pathway_goals_wide
    description: "\n
    Author:  Caitlin Dugan\n
    Purpose: List of member goals as boolean fields and created at dates. This table was created to remove duplication that occured when comparing dates to dates in other tables.\n
    "
    columns:
      - name: patientId
        tests:
          - unique
          - not_null

  - name: mrt_care_pathway_historical_assignment_all
    description: Record of all pathway assignments and rankings, with creation and deletion timestamps, and top current flag
    tests:
      - maximum_distinct_values:
          columns_to_group: patientId, pathwaySlug
          column_to_count: memberPathwayRank
          where: "deletedAt is null"
    columns:
      - name: assignmentId
        tests:
          - not_null
          - unique
      - name: patientId
        tests:
          - not_null
      - name: pathwaySlug
        tests:
          - not_null
      - name: memberPathwayRank
        tests:
          - not_null
      - name: createdAt
        tests:
          - not_null
      - name: deletedAt
      - name: isCurrentPathway
      - name: isTopCurrentPathway

  - name: mrt_care_pathway_savings
    description: Projected monthly savings by member, based on top algorithmically-assigned pathway
    columns:
      - name: patientId
        tests:
          - not_null
          - unique
      - name: topPathwaySlug
        tests:
          - not_null
      - name: savingsDollarsPerMemberMonth
      - name: planPaidDollarsPerMemberMonth
      - name: memberMonths
        tests:
          - not_null
