version: 2

models:
  - name: qm_service_reporting
    description: "\n
    Author: Caitlin Dugan\n
    Purpose: Reshape computed candidate results for integration with Able gaps an QM service"

    columns:
      - name: patientID
        description: Cityblock assigned member identifier
        tests:
          - not_null
      - name: partnerName
      - name: reportingYear
      - name: reportingMonth
      - name: reportingWeek
      - name: eligMonthFlag 
      - name: eligNowFlag
      - name: measurename
      - name: ableDenomFlag
      - name: denomYear
      - name: consentedEnrolledByApril         
      - name: consentedEnrolledByApril          
      - name: denomMonth
      - name: minClosedProv
        description: Date first provisionally closed in Commons
      - name: minClosedAll
        description: Date first closed in Able or Commons
      - name: minClosedAny
        description: Date first provisionally closed or closed in Able or Commons

models:
  - name: qm_service_reporting
    description: "\n
    Author: Caitlin Dugan\n
    Purpose: LTSS Calculator moved from a worksheet to a dbt model to support the Tufts care team. Can eventually be used for multiple markets if needed."
