
# all payer data sources

version: 2

sources:

  - name: cardinal
    description: Cardinal gold data
    database: cbh-cardinal-data
    schema: gold_claims

    tables:
      - name: Facility
      - name: Pharmacy
      - name: Professional
      - name: Provider

  - name: cardinal_silver
    description: Cardinal silver data
    database: cbh-cardinal-data
    schema: silver_claims

    tables:
      - name: Member_*

  - name: carefirst
    description: CareFirst gold data
    database: cbh-carefirst-data
    schema: gold_claims

    tables:
      - name: Facility
      - name: LabResult
      - name: Pharmacy
      - name: Professional
      - name: Provider

  - name: carefirst_silver
    description: CareFirst silver data
    database: cbh-carefirst-data
    schema: silver_claims

    tables:
      - name: member_month_*
      - name: provider
      - name: member_demographics_*
      - name: facility_*

  - name: carefirst_historic
    description: CareFirst raw historic data
    database: cbh-partner-integrations
    schema: carefirst_dc

    tables:
      - name: HistoricalClaimData_20201002
    
  - name: cci
    description: Connecticare gold data
    database: connecticare-data
    schema: gold_claims

    tables:
      - name: Facility
      - name: LabResult
      - name: Member
      - name: Pharmacy
      - name: PriorAuthorization_*
      - name: Professional
      - name: Provider

  - name: cci_facets
    description: Connecticare gold facets data
    database: connecticare-data
    schema: gold_claims_facets

    tables:
      - name: Member
      - name: Member_*
      - name: MemberV2_*
      - name: Provider

  - name: cci_silver
    description: Connecticare silver data
    database: connecticare-data
    schema: silver_claims

    tables:
      - name: Member_2*
      - name: Member_med_2*
      - name: SuspectCodes_*

  - name: cci_silver_dsnp
    description: Connecticare silver DSNP data one-time shipment
    database: connecticare-data
    schema: silver_claims_dsnp

    tables:
      - name: Member_med_20200526

  - name: cci_facets_silver
    description: Connecticare silver data
    database: connecticare-data
    schema: silver_claims_facets

    tables:
      - name: Member_Facets_med_*
      - name: Attributed_PCP_med_*

  - name: cci_cms_revenue
    description: Connecticare MMR and MOR Files
    database: connecticare-data
    schema: cms_revenue

    tables:
      - name: mor_hccmodd_3528_*
      - name: mmr_monmemd_3528_*
      - name: mor_hccmodd_3276_*
      - name: mmr_monmemd_3276_*

  - name: emblem
    description: Emblem gold data
    database: emblem-data
    schema: gold_claims

    tables:
      - name: Facility
      - name: LabResult
      - name: Member
      - name: Pharmacy
      - name: PriorAuthorization
      - name: PriorAuthorization_*
      - name: Professional
      - name: Provider

  - name: emblem_silver
    description: Emblem silver data
    database: emblem-data
    schema: silver_claims

    tables:
     - name: facility
     - name: member_month
     - name: member_month_*
     - name: member_demographics
     - name: member_demographics_*
     - name: professional
     - name: pharmacy
     - name: providers
     - name: providers_*
     - name: SuspectCodes_*

  - name: emblem_silver_v2
    description: Emblem silver data, version 2 schemas
    database: emblem-data
    schema: silver_claims_v2

    tables:
      - name: control_v2_*

      - name: facility_ext_v2_*
        tests:
          - record_difference_percentage_within_range:
              control_total_file_name_root: FACEXTN
        columns:
          - name: data.CLAIM_ID
            tests:
              - not_null

      - name: facility_v2_*
        tests:
          - record_difference_percentage_within_range:
              has_line_of_business_totals: true
              control_total_file_name_root: FACCLM
        columns:
          - name: data.CLAIM_ID
            tests:
              - not_null

      - name: lab_results_v2_*
        tests:
          - record_difference_percentage_within_range:
              has_line_of_business_totals: true
              control_total_file_name_root: LABRSLT

      - name: member_demographics_v2_*
        tests:
          - record_difference_percentage_within_range:
              has_line_of_business_totals: true
              control_total_file_name_root: MEMDEMO

      - name: member_month_v2_*
        tests:
          - record_difference_percentage_within_range:
              control_total_file_name_root: MEMMNTH

      - name: pharmacy_v2_*
        tests:
          - record_difference_percentage_within_range:
              has_line_of_business_totals: true
              control_total_file_name_root: PHRMCLM
        columns:
          - name: data.CLM_NBR
            tests:
              - not_null

      - name: professional_ext_v2_*
        tests:
          - record_difference_percentage_within_range:
              control_total_file_name_root: PROFEXTN
        columns:
          - name: data.CLAIM_ID
            tests:
              - not_null

      - name: professional_v2_*
        tests:
          - record_difference_percentage_within_range:
              has_line_of_business_totals: true
              control_total_file_name_root: PROFCLM
        columns:
          - name: data.CLAIM_ID
            tests:
              - not_null

      - name: providers_v2_*
        tests:
          - record_difference_percentage_within_range:
              control_total_file_name_root: PROV

  - name: emblem_virtual
    description: Emblem gold data for medicaid digital cohort
    database: emblem-data
    schema: gold_claims_virtual

    tables:
      - name: Facility
      - name: LabResult
      - name: Member
      - name: Pharmacy
      - name: Professional
      - name: Provider

  - name: emblem_silver_virtual
    description: Emblem silver data for medicaid digital cohort
    database: emblem-data
    schema: silver_claims_virtual

    tables:
     - name: member_month
     - name: member_month_*
     - name: member_demographics_*
     - name: providers_*

  - name: emblem_revenue
    description: Emblem revenue data for medicare members
    database: emblem-data
    schema: cms_revenue

    tables:
     - name: MMR_20*

  - name: emblem_revenue_mor
    description: Emblem revenue data for medicare members
    database: emblem-data
    schema: revenue

    tables:
     - name: MOR_20*

  - name: healthy_blue
    description: Healthy Blue gold data
    database: cbh-healthyblue-data
    schema: gold_claims

    tables:
      - name: Facility
      - name: Pharmacy
      - name: Professional
      - name: Provider
           
  - name: healthy_blue_silver
    description: Healthy Blue silver data
    database: cbh-healthyblue-data
    schema: silver_claims

    tables:
      - name: member_*

  - name: tufts
    description: Tufts gold data
    database: tufts-data
    schema: gold_claims

    tables:
      - name: Facility
      - name: Member
      - name: Member_*  
      - name: Member_20200213
      - name: Member_Daily_*  
      - name: Professional
      - name: Provider
      - name: Pharmacy

  - name: tufts_revenue
    description: Tufts revenue data for medicare members
    database: tufts-data
    schema: cms_revenue

    tables:
     - name: mmr_monmemd_7419_*
     - name: mor_hccmodd_7419_*
     
  - name: tufts_silver
    description: Tufts silver data
    database: tufts-data
    schema: silver_claims

    tables:
      - name: MassHealth_*
      - name: Member_*
      - name: Member_20200213
      - name: Member_Daily_*
      - name: PriorAuthorizationAdmission_*
        columns:
          - name: patient.externalId
            tests:
              - not_null
      - name: PriorAuthorizationReferral_*
        columns:
          - name: patient.externalId
            tests:
              - not_null

    # Temporary: Lesli Cost & Use
  - name: cost_and_use
    description: Cost and use data generated by Lesli's R-script
    database: cityblock-analytics
    schema: uploads

    tables:
      - name: eh_cu_claims_recent_month_f
        columns:
            - name: patientId
              description: "Primary identifier for patient"
              tests:
                  - not_null
            - name: CLAIM_ID
              description: "Primary identifier for each claim line"
            - name: pat_clm_id
              description: "Primary identifier for each claim line with patient to avoid duplicates"

      - name: eh_all_claims_recent_month_f

  # Temporary: Andy member management
  - name: member_management
    description: Member management fuzzy match data generated by Andy's Python script; older cb_cohort emblem files
    database: cityblock-analytics
    schema: uploads

    tables:
      - name: fuzzy_match_results
      - name: CB_COHORT_MEMBERDEMO_EXTRACT_*
      - name: CB_COHORT_MEMBERMONTH_EXTRACT_*
      - name: bad_dupes
      - name: cohort8_from_digital_patientId_list
      - name: cohort9_from_digital_patientId_list

  # Temporary: Tufts supplemental phone numbers (for use in Karuna comms mart)
  - name: tufts_phone_numbers
    description: Phone numbers provided in Tufts roster file, cleaned up and uploaded by Andy
    database: cityblock-analytics
    schema: uploads

    tables:
      - name: tufts_phone_numbers_supplemental_cleaned
