steps:
  - name: gcr.io/cloud-builders/gcloud@sha256:b3d20985cc0e73d3a2c3c890c5c9ddedfe865339a93ab669f31007b5b2cad84d # version as of June 26 2020
    id: get-svc-acct-creds-and-clone-repo
    entrypoint: bash
    args:
      - '-c'
      - >-
        gcloud beta secrets versions access 1 --secret dbt_prod --project cbh-secrets  > /var/secrets/google/key.json
        && cd /mirror
        && gcloud source repos clone github_cityblock_mixer
    volumes:
      - name: svc_acct_creds
        path: /var/secrets/google
      - name: mirror
        path: /mirror
  - name: gcr.io/cloud-builders/git
    id: checkout-prev-commit-and-find-models-to-run
    waitFor:
      - get-svc-acct-creds-and-clone-repo
    entrypoint: bash
    args:
      - '-c'
      - >-
        cd /mirror/github_cityblock_mixer && git checkout HEAD~1 &&
        bash /workspace/dbt/scripts/models_changed.sh /mirror/github_cityblock_mixer/dbt /workspace/dbt /workspace/models.txt
    env:
      - _BUILD_ID=$BUILD_ID
    volumes:
      - name: mirror
        path: /mirror
  - name: gcr.io/cityblock-data/dbt-base:latest
    id: dbt-run
    waitFor:
      - get-svc-acct-creds-and-clone-repo
      - checkout-prev-commit-and-find-models-to-run
    entrypoint: bash
    args:
      - '-c'
      - >-
        if [[ -f /workspace/models.txt ]]; then
        dbt deps && dbt seed
        && dbt run --fail-fast --target prod --models $(cat /workspace/models.txt) --exclude tag:evening
        && dbt test --target prod --models $(cat /workspace/models.txt) --exclude tag:evening
        && (dbt docs generate || echo "dbt docs generate failed" && exit 0); else echo "No dbt changes to run"; fi
        # TODO exit because can't get information schema for public datasets
    env:
      - GOOGLE_APPLICATION_CREDENTIALS=/var/secrets/google/key.json
      - DBT_PROFILES_DIR=/workspace/dbt/cloud_build/prod
      - CITYBLOCK_ANALYTICS=cityblock-analytics
    dir: dbt
    volumes:
      - name: svc_acct_creds
        path: /var/secrets/google
  - name: gcr.io/cloud-builders/gcloud@sha256:b3d20985cc0e73d3a2c3c890c5c9ddedfe865339a93ab669f31007b5b2cad84d
    id: upload-docs-to-gcs
    waitFor:
      - dbt-run
    entrypoint: bash
    args:
      - '-c'
      - >-
        if [[ -d /workspace/dbt/target ]]; then
        gsutil -m rsync -r /workspace/dbt/target gs://cbh-analytics-artifacts/dbt_docs/; else echo "No docs to update"; fi

timeout: 10000s
logsBucket: gs://cbh-cloud-build-logs/dbt-prod
