dsa:
  target: prod
  outputs:
    prod:
      type: bigquery
      method: service-account
      project: cityblock-analytics
      dataset: prod
      threads: 12
      keyfile: /var/secrets/google/key.json
      timeout_seconds: 300
      location: US
