version: 2

models:
  - name: stg_commons_member_phones
    description: Latest Commons record for a given member phone
    columns:
      - name: id
        description: Unique identifier, based on `memberId` and `phone`
        tests:
          - unique
          - not_null
      - name: source
        tests:
          - accepted_values:
              values: ['commons']
      - name: memberId
      - name: phone
        tests:
          - accepted_length:
              column_length: 10
      - name: phoneType
      - name: isPrimaryPhone
        tests:
          - not_null
      - name: createdAt

  - name: stg_service_member_phones
    description: Latest service record for a given member phone
    columns:
      - name: id
        description: Unique identifier, based on `memberId` and `phone`
        tests:
          - unique
          - not_null
      - name: source
        tests:
          - accepted_values:
              values: ['service']
      - name: memberId
      - name: phone
      - name: phoneType
      - name: isPrimaryPhone
        tests:
          - not_null
      - name: createdAt
