# file name prefixed with "member_service_" b/c flex app engine can't have a cloudbuild.yaml in same directory as app.yaml (pulled here)
# see for more: https://github.com/GoogleCloudPlatform/cloud-builders/issues/397
steps:
  - name: "node:10"
    id: install-node-dependencies
    entrypoint: npm
    args:
      - "install"
    dir: ${_SERVICE_DIR}
    waitFor: ["-"]

  - name: "gcr.io/cloudsql-docker/gce-proxy:1.15"
    id: cloud-sql-proxy
    entrypoint: sh
    args:
      - "-c"
      - >-
        /cloud_sql_proxy -dir=/cloudsql -instances=${_CLOUD_SQL_INSTANCE} & while [ ! -f /cloudsql/stop ]; do sleep 2; done
    timeout: 600s
    waitFor: ["-"]
    volumes:
      - name: "db"
        path: "/cloudsql"

  - name: "node:10"
    id: db-migrations
    entrypoint: "sh"
    secretEnv: [DB_USER, DB_PASSWORD]
    args:
      - "-c"
      - >-
        export DB_USER=$$DB_USER && DB_PASSWORD=$$DB_PASSWORD && npm run migrate && touch /cloudsql/stop
    env:
      [
        "NODE_ENV=${_NODE_ENV}",
        "DB_HOST=/cloudsql/${_CLOUD_SQL_INSTANCE}",
        "DB_NAME=${_DB_NAME}"
      ]
    volumes:
      - name: "db"
        path: "/cloudsql"
    dir: ${_SERVICE_DIR}
    waitFor:
      - install-node-dependencies

  - name: "gcr.io/cloud-builders/gcloud"
    id: deploy-app
    waitFor:
      - db-migrations
    entrypoint: "bash"
    # have to pull [env]-member-service-app-yaml directly b/c using availbleSecrets/secretEnv does not output new lines in yaml
    args:
      - "-c"
      - >-
        gcloud secrets versions access latest --secret=${_DEPLOY_ENV}-member-service-app-yaml --project=${_SECRETS_PROJECT} > app.yaml
        && gcloud app deploy app.yaml --project=${_APP_PROJECT}

substitutions:
  _SERVICE_DIR: services/member_service
  # other substitutions defined in terraform/src/custom/quality_measure_service/main.tf
availableSecrets:
  secretManager:
    - versionName: "projects/${_SECRETS_PROJECT}/secrets/${_DEPLOY_ENV}-member-service-db-service-user-name/versions/latest"
      env: DB_USER
    - versionName: "projects/${_SECRETS_PROJECT}/secrets/${_DEPLOY_ENV}-member-service-db-service-user-password/versions/latest"
      env: DB_PASSWORD
timeout: 1200s
logsBucket: gs://cbh-cloud-build-logs/build-${_DEPLOY_ENV}-member-service
