version: 2

models:
  - name: computed_hcc_gaps
    description: "\n
    Author: Katie Claiborne\n
    Purpose: Reshape computed candidate results for integration with Able gaps"

  - name: member_latest_hccs
    description: "\n
    Author: Andy Seiden\n
    Purpose: Allows for population level view of HCC prevalences, beyond just the top 2 HCCs per member. Contains each member's most severe HCC per hccRollup, from the latest calendar year with 9mo of claims runout. Grain = member & hcc. "

  - name: opptys_ml_suspect_all
    description: "\n
    Author: Caitlin Dugan\n
    Purpose: Combined list of ML-derived opportunities from DS ML models"

  - name: opptys_rb_suspect_computed
    description: "\n
    Author: Caitlin Dugan\n
    Purpose: Combined list of rules-based opportunities based on previously created computed fields"

  - name: opptys_rb_suspect_diab
    description: "\n
    Author: Caitlin Dugan\n
    Purpose: Combined list of rules-based opportunities focused on diabetes. Includes lab, pharm, dx, cpt sources of suspects"

  - name: opptys_rb_suspect_diab_comp
    description: "\n
    Author: Caitlin Dugan\n
    Purpose: Combined list of rules-based opportunities focused on diabetes with complications. Includes lab, pharm, dx, cpt sources of suspects"

  - name: opptys_recapture_all
    description: "\n
    Author: Caitlin Dugan\n
    Purpose: All suspect and persistent opportunities derived from payer and Able"

  - name: risk_claims_cpt
    description: "\n
    Author: Caitlin Dugan\n
    Purpose: List of patients with with any attribution history between 2017 and 2020 and their respective cpt codes for the past 3 years, used to drive rules-based suspects"

  - name: risk_claims_dx
    description: "\n
    Author: Caitlin Dugan\n
    Purpose: List of patients with with any attribution history between 2017 and 2020 and their respective dx codes for the past 3 years, used to drive rules-based suspects"

  - name: risk_claims_lab
    description: "\n
    Author: Caitlin Dugan\n
    Purpose: List of patients with any attribution history between 2017 and 2020 and their respective lab/LOINC codes for the past 3 years, used to drive rules-based suspects"

  - name: risk_claims_patients
    description: "\n
    Author: Caitlin Dugan\n
    Purpose: List of patients with any attribution history between 2017 and 2020 to be included in 2019/2020 risk models"

  - name: risk_claims_pharm
    description: "\n
    Author: Caitlin Dugan\n
    Purpose: List of patients with any attribution history between 2017 and 2020 and their respective NDC codes for the past 3 years, used to drive rules-based suspects"