version: 2

models:
  - name: abs_cotiviti_historical_output_predictions
    description: Historical Cotiviti predictions for each member, for each model trained on the population they were a member of at the time.
    columns:
      - name: id
        description: Unique identifier based on hash of `patientId`, `modelId`, `ModelBasePeriodStart` and `ModelBasePeriodEnd`, defined in the `abs_cotiviti_member_selected_historical_runs` model
        tests:
          - unique
          - not_null
      - name: patientId
        tests:
          - not_null
      - name: modelId
        tests:
          - not_null
      - name: runId
        tests:
          - not_null
      - name: predictionValue
        tests:
          - not_null
      - name: modelName
        tests:
          - not_null
      - name: ModelBasePeriodStart
        tests:
          - not_null
      - name: ModelBasePeriodEnd
        tests:
          - not_null
      - name: createdAt
        tests:
          - not_null

  - name: abs_cotiviti_latest_output_predictions
    description: Limits output predictions to latest model run and target population
    columns:
      - name: id
        description: Unique prediction ID, generated in the `abs_cotiviti_member_selected_historical_runs` model
        tests:
          - unique
          - not_null
      - name: patientId
        tests:
          - not_null
      - name: modelId
        tests:
          - not_null
      - name: runId
        tests:
          - not_null
      - name: predictionValue
        tests:
          - not_null
      - name: modelName
        tests:
          - not_null
      - name: ModelBasePeriodStart
        tests:
          - not_null
      - name: ModelBasePeriodEnd
        tests:
          - not_null
      - name: createdAt
        tests:
          - not_null

  - name: abs_cotiviti_member_selected_historical_runs
    description: Selected Cotiviti prediction runs for each member, prediction type, and base period
    tests:
      - unique:
          column_name: "concat(patientId, predictionTime, predictionScoreType, predictionTargetEvent, predictionTargetExpenditureType, ModelBasePeriodStart)"
    columns:
      - name: id
        description: Unique identifier based on hash of `patientId`, `modelId`, `ModelBasePeriodStart` and `ModelBasePeriodEnd`
        tests:
          - not_null
          - unique
      - name: patientId
        tests:
          - not_null
      - name: runId
        tests:
          - not_null
      - name: modelId
        tests:
          - not_null
      - name: modelName
        tests:
          - not_null
      - name: modelTargetPopulation
        description: The LOB of the population the Cotiviti model was trained on
        tests:
          - not_null
      - name: memberPopulation
        description: The recorded LOB of the member at the end of the model run
      - name: ModelBasePeriodStart
        tests:
          - not_null
      - name: ModelBasePeriodEnd
        tests:
          - not_null
      - name: predictionScoreType
        tests:
          - not_null
      - name: predictionTime
        tests:
          - not_null
      - name: predictionTargetEvent
      - name: predictionTargetExpenditureType
      - name: createdAt
        description: Timestamp when the prediction was generated

  - name: abs_cotiviti_output_member_data
    description: Limited to records for which member was in target population
    tests:
      - dbt_utils.expression_is_true:
          expression: "IS_TARGET_POPULATION"

  - name: abs_cotiviti_output_risk_driver_categories
    description: Model output with risk drivers categorized into physical, behavioral and social drivers
    columns:
      - name: patientId
        tests:
          - not_null
      - name: modelId
        tests:
          - not_null
      - name: runId
        tests:
          - not_null
      - name: riskContributionPhysicalPercent
        description: Percentage of the model score that has been attributed to physical risk factors
        tests:
          - not_null
      - name: riskContributionBehavioralPercent
        description: Percentage of the model score that has been attributed to behavioral risk factors
        tests:
          - not_null
      - name: riskContributionSocialPercent
        description: Percentage of the model score that has been attributed to social risk factors
        tests:
          - not_null
      - name: riskContributionTotalPercent
        description: Total percentage of the model score that has been attributed to any risk factors
        tests:
          - not_null
      - name: normalizedRiskContributionPhysicalPercent
        description: Percentage attributed to physical risk factors, normalized by total percentage attributed
        tests:
          - not_null
      - name: normalizedRiskContributionBehavioralPercent
        description: Percentage attributed to behavioral risk factors, normalized by total percentage attributed
        tests:
          - not_null
      - name: normalizedRiskContributionSocialPercent
        description: Percentage attributed to social risk factors, normalized by total percentage attributed
        tests:
          - not_null

  - name: abs_cotiviti_output_normalized_relative_risk_scores
    description: For Cotiviti predictions that are risk scores either related to predicted cost or utilization, compute risk normalized to our own population
    columns:
      - name: patientId
        tests:
          - not_null
      - name: modelId
        tests:
          - not_null
      - name: runId
        tests:
          - not_null
      - name: predictionTime
        tests:
          - not_null
          - accepted_values:
              values: ['concurrent', 'prospective']
      - name: predictionTargetEvent
      - name: predictionTargetExpenditureType
      - name: individualRRS
        description: Raw Cotiviti model output, known as `predictionValue` elsewhere
        tests:
          - not_null
      - name: populationAverageRRS
        description: Average risk score for the population that the model was run on
          - not_null
      - name: isWeightedByMonthsEligible
        description: Indicates whether the population average was computed by weighting each score by number of months eligible
        tests:
          - accepted_values:
              values: [true, false]
              quote: false
      - name: normalizedRRS
        tests:
          - not_null
      - name: createdAt
        tests:
          - not_null

  - name: abs_cotiviti_output_predicted_expenditures
    description: Uses normalized risk scores and average expenditures per run to compute predicted expenditures
    columns:
      - name: patientId
        tests:
          - not_null
      - name: modelId
        tests:
          - not_null
      - name: predictionTime
        tests:
          - not_null
          - accepted_values:
              values: ['concurrent', 'prospective']
      - name: expenditureType
        tests:
          - not_null
          - accepted_values:
              values: ['Medical', 'Pharmacy', 'Medical + Pharmacy']
      - name: individualRRS
        tests:
          - not_null
      - name: populationAverageRRS
        tests:
          - not_null
      - name: normalizedRRS
        tests:
          - not_null
      - name: populationAverageAnnualizedCostPMPY
        description: Actual population average cost per member per year, annualized assuming average cost is the same for missing months
        tests:
          - not_null
      - name: expectedAnnualizedCostPMPY
        tests:
          - not_null
      - name: populationAverageCostPMPM
        tests:
          - not_null
      - name: expectedCostPMPM
        description: Expected cost for the member per month
        tests:
          - not_null
      - name: runId
        tests:
          - not_null
      - name: createdAt
        tests:
          - not_null
