
version: 2

models:
  - name: mrt_prior_auth_emblem_cci
    description: Expanded and flattened version of latest Emblem and CCI authorizations
    columns:
      - name: id
        description: >
          Unique identifier, based on `memberAuthorizationId`, `diagnosisCode`,
          `procedureCode`, and `procedureServiceUnits`
        tests:
          - unique
          - not_null

  - name: mrt_prior_auth_tufts
    description: Combines latest records to authorization-code level; adds code descriptions for reference
    tests:
      - unique:
          column_name: "concat(authorizationNumber, diagnosisCode, procedureCode)"
          severity: warn
    columns:
      - name: fileName
      - name: receivedDate
      - name: authorizationNumber
      - name: authorizationStatus
      - name: authorizationCertificationDate
      - name: authorizationStartDate
      - name: authorizationEndDate
      - name: patientId
      - name: externalId
      - name: memberName
      - name: memberAddress
      - name: memberCity
      - name: memberState
      - name: memberZip
      - name: requestingProviderNpi
      - name: requestingProviderName
      - name: requestingProviderAddress1
      - name: requestingProviderAddress2
      - name: requestingProviderCity
      - name: requestingProviderState
      - name: requestingProviderZip
      - name: requestingProviderPhone
      - name: servicingProviderNpi
      - name: servicingProviderName
      - name: servicingProviderAddress1
      - name: servicingProviderAddress2
      - name: servicingProviderCity
      - name: servicingProviderState
      - name: servicingProviderZip
      - name: servicingProviderPhone
      - name: diagnosisCode
      - name: diagnosisCodeDescription
      - name: procedureCode
      - name: procedureCodeDescription
      - name: modifierCode
      - name: totalApprovedProcedureCount
      - name: admissionDate
      - name: facilityNpiTin
      - name: approvedLengthOfStay
      - name: authorizedBedType
      - name: authorizedBedTypeDescription
      - name: authorizedBedTypeStatus
      - name: minAuthorizedBedTypeStartDate
      - name: maxAuthorizedBedTypeEndDate
