version: 2

macros:
  - name: mcr_claims_pivot_encounters
    description: Creates pivoted counts of encounter types based on claims self-service flags
    arguments:
      - name: encounter_configs
        type: list
        description: List of dictionaries containing `flag_prefix` and `count_root` keys
      - name: count_prefix
        type: string
        description: Prefix for resulting count fields
