version: 2

models:
  - name: abs_prior_auth_emblem_cci_version_received_dates
    description: Identifies earliest receipt of Emblem and CCI authorization versions over time
    columns:
      - name: id
        description: >
          Unique identifier based on `patientId`, `authorizationId`, `admitDate`,
          `facilityName`, and `isConcurrentInpatientAuthorization`
        tests:
          - unique
          - not_null
      - name: patientId
        tests:
          - not_null
      - name: receivedDate
        description: Earliest CBH file receipt date of authorization version, based on table suffix
        tests:
          - not_null
      - name: isConcurrentInpatientAuthorization
        description: >
          Indicates whether authorization is for concurrent inpatient admission, based on non-null `admitDate`,
          `placeOfService` of 'Inpatient Hospital', `careType` of 'Emergency' or 'Urgent',
          and `caseType` of 'Concurrent'
        tests:
          - not_null
      - name: wasReceivedWithinThreeDaysOfAdmit
        description: >
          Indicates whether earliest receipt of authorization version was within three days of admission,
          based on `receivedDate` and `admitDate`
        tests:
          - not_null

  - name: abs_prior_auth_emblem_cci_latest_version_dates
    description: Identifies member authorization dates, based on latest received version
    columns:
      - name: id
        description: Unique identifier based on `patientId`, `authorizationId`, and `isConcurrentInpatientAuthorization`
        tests:
          - unique
          - not_null
      - name: authorizationVersionId
        description: Authorization version identifier, produced in `abs_prior_auth_emblem_cci_version_received_dates`

  - name: abs_prior_auth_tufts_all
    description: Incremental table collecting daily Tufts authorizations over time
    columns:
      - name: fileName
        description: Indicates silver prior authorization table of origin
        tests:
          - accepted_values:
              values: ['Admission', 'Referral']
          - not_null
      - name: receivedDate
        description: Derived from table suffix in wildcard union
        tests:
          - not_null
      - name: authorizationNumber
        description: Identifier connecting records for a given authorization
      - name: authorizationStatus
      - name: authorizationCertificationDate
      - name: authorizationStartDate
      - name: authorizationEndDate
      - name: patientId
      - name: externalId
      - name: memberName
      - name: memberAddress
      - name: memberCity
      - name: memberState
      - name: memberZip
      - name: requestingProviderNpi
      - name: requestingProviderName
      - name: requestingProviderAddress1
      - name: requestingProviderAddress2
      - name: requestingProviderCity
      - name: requestingProviderState
      - name: requestingProviderZip
      - name: requestingProviderPhone
      - name: servicingProviderNpi
      - name: servicingProviderName
      - name: servicingProviderAddress1
      - name: servicingProviderAddress2
      - name: servicingProviderCity
      - name: servicingProviderState
      - name: servicingProviderZip
      - name: servicingProviderPhone
      - name: diagnosisCodes
      - name: procedureCode
      - name: modifierCode
      - name: approvedProcedureCount
      - name: admissionDate
      - name: facilityNpiTin
      - name: approvedLengthOfStay
      - name: authorizedBedType
      - name: authorizedBedTypeDescription
      - name: authorizedBedTypeStatus
      - name: authorizedBedTypeStartDate
      - name: authorizedBedTypeEndDate

  - name: abs_prior_auth_tufts_latest
    description: "\n
    Most recently received records for a given authorization\n
    Schema matches abs_prior_auth_tufts_all\n
    "
    tests:
      - maximum_distinct_values:
          columns_to_group: authorizationNumber
          column_to_count: receivedDate
