
version: 2

models:

  - name: abs_legacy_prioritization
    description: "
    - Author: \n
    - Purpose: \n
    "
    columns:
     - name: patientId


  - name: abs_member_programs
    description: "
    - Author: \n
    - Purpose: \n
    "
    columns:
     - name: patientId
     - name: outreachPriority


  - name: abs_outreach_prioritization
    description: "
    - Author: \n
    - Purpose: \n
    "
    columns:
     - name: patientId
     - name: rank
     - name: isPriority
     - name: createdDate
     - name: deletedDate
     - name: market


  - name: sct_member_list
    description: "
    - Author: Caitlin Dugan\n
    - Purpose: Incremental model created by Sara in support of the SCT program\n
    "
    columns:
      - name: PatientID
        tests:
          - not_null
      - name: MemberFullName
      - name: MemberName
      - name: CurrentState
      - name: Careteam
      - name: Superutilizer
      - name: MemberLosttocontact
      - name: Membernotinterested
      - name: Pathway
      - name: Pod
      - name: Review
      - name: AssignedPHIProgram
      - name: SCTReviewComplete
      - name: SCTReviewDate
      - name: MonthofSCTReview
      - name: SCTOwner
      - name: Followupdate
      - name: SCTStatus
      - name: RiskScore
      - name: LikelytoReadmit
      - name: ClinicalCondtion1
      - name: Appropriate1
      - name: ClinicalCondition2
      - name: Appropriate2
      - name: ClinicalCondition3
      - name: Appropriate3
      - name: ClinicalCondition4
      - name: Appropriate4
      - name: ClinicalCondition5
      - name: Appropriate5
      - name: Needmedicalrecords
      - name: Typeofmedicalrecords
      - name: Institution
      - name: CRRMeetAndGreet
      - name: Referral