version: 2

models:
  - name: abs_diagnoses
    description: Collection of diagnoses from claims (facility and professional), EHR problems and encounters, and HIE events
    columns:
      - name: id
        description: Non-unique identifier based on `sourceId`, `diagnosisCode`, `serviceDateFrom`, and `encounterType`
        tests:
          - not_null
