steps:
  - name: gcr.io/cloud-builders/gcloud:latest
    id: get-svc-acct-creds
    waitFor: ['-']
    entrypoint: bash
    args:
      - '-c'
      - >-
        gcloud beta secrets versions access 1 --secret dbt-run-staging --project
        cbh-analytics-staging  > /var/secrets/google/key.json
    volumes:
      - name: svc_acct_creds
        path: /var/secrets/google
  - name: gcr.io/cloud-builders/gcloud
    id: clone-repo
    waitFor: ['-']
    entrypoint: bash
    args:
      - -c
      - cd /mirror && gcloud source repos clone github_cityblock_mixer
    volumes:
      - name: mirror
        path: /mirror
  - name: gcr.io/cloud-builders/git
    id: find-models-to-run
    waitFor:
      - clone-repo
    entrypoint: bash
    args:
      - -c
      - ./scripts/models_changed.sh /mirror/github_cityblock_mixer/dbt /workspace/dbt /workspace/models.txt
    dir: dbt
    env:
      - _BUILD_ID=$BUILD_ID
    volumes:
      - name: mirror
        path: /mirror
  - name: gcr.io/cityblock-data/dbt-base:latest
    id: dbt-run
    waitFor:
      - get-svc-acct-creds
      - find-models-to-run
    entrypoint: bash
    args:
      - '-c'
      - if [[ -f /workspace/models.txt ]]; then
        dbt deps && dbt seed
        && dbt run --fail-fast --target staging --models $(cat /workspace/models.txt) --full-refresh
        && dbt test --target staging --models $(cat /workspace/models.txt); fi
    env:
      - GOOGLE_APPLICATION_CREDENTIALS=/var/secrets/google/key.json
      - DBT_PROFILES_DIR=/workspace/dbt/cloud_build/staging
      - CITYBLOCK_ANALYTICS=cbh-analytics-staging
    dir: dbt
    volumes:
      - name: svc_acct_creds
        path: /var/secrets/google

timeout: 3600s
logsBucket: gs://cbh-cloud-build-logs/dbt-staging
