dsa:
  target: staging
  outputs:
    staging:
      type: bigquery
      method: service-account
      project: cbh-analytics-staging
      dataset: prod
      threads: 12
      keyfile: /var/secrets/google/key.json
      timeout_seconds: 300
      location: US
