
version: 2

models:
  - name: abs_elation_appointment_statuses
    description: >
      Identifies Cityblock member and user IDs associated with Elation appointments,
      adds `isClinicalIntakeAppointment` flag based on appointment type,
      and identifies corresponding Commons appointment ID
    columns:
      - name: ehrAppointmentId
        description: Inherited appointment identifier from Elation mirror. Not unique because each appointment can contain multiple status updates.
        tests:
          - not_null
      - name: patientId
        tests:
          - not_null
      - name: isClinicalIntakeAppointment
        description: >
          Flags clinical intake appointments via business logic: where appointment_type starts with with the string 'Annual Provider Visit' or 'Medical Intake' and
          ends with 'Home', 'Hub', or 'Televideo' (only certain modalities count as clinical intakes)
        tests:
          - not_null

  - name: abs_epic_appointment_statuses
    description: >
      Extracts epic appointment data from streaming redox json format.
      Identifies Cityblock member ID and provider NPI associated with Epic appointments,
      adds `isClinicalIntakeAppointment` flag based on appointment type,
      and identifies corresponding Commons appointment ID
    columns:
      - name: ehrAppointmentId
        description: Inherited appointment identifier from Epic redox streaming VisitNumber. Not unique because each appointment can contain multiple status updates.
        tests:
          - not_null
      - name: isClinicalIntakeAppointment
        description: >
          Flags clinical intake appointments via business logic:
          - where epic/redox encounter.reason.name contains the string 'Clinical Intake'
          - where epic/redox encounter.type.name does not contain the string 'Telephon'
        tests:
          - not_null

  - name: abs_ehr_appointment_statuses
    description: >
      Grain of the table is at the appointment status change level. Every time an appt status changes there is a new row.
      intermediate model unioning appointment data from EHRs (epic and elation), 
      before joining to commons appointment table,
      in order to produce the member_appointment_statuses view in looker
    
