version: 2

macros:
  - name: assessment_score
    description: >
      Produces value of 'true' for members with assessment from provided list and associated score.
      Optionally, a gender-specific score can be incorporated.
    arguments:
      - name: slug
        type: string
        description: Required; slug to associate with field
      - name: assessment_slug
        type: list
        description: Required; list of slugs for which member should have value of 'true'
      - name: eligible_gender
        type: string
        description: Optional; used for gender-specific scores
      - name: period
        type: string
        description: Optional; filters results to within the selected time period

  - name: boolean_evidence
    description: >
      Produces value of 'true' for members with value of 'true' in one or more fields from given list.
      Optionally, limits value of 'true' to members without value of 'true' in any field from second list.
    arguments:
      - name: slug
        type: string
        description: Required; slug to associate with field
      - name: condition_slugs
        type: list
        description: Required; list of slugs for which member should have value of 'true'
      - name: min_conditions
        type: integer
        description: Required; number of `condition_slugs` for which member should have value of 'true' (defaults to 1)
      - name: excluded_condition_slugs
        type: list
        description: >
          Optional; list of slugs for which member should not have value of 'true'
          If provided, a value of 'true' in any field will exclude member from value of 'true'

  - name: diagnosis_evidence
    description: Produces value of 'true' for members with diagnosis or procedure from provided codes or value set
    arguments:
      - name: slug
        type: string
        description: Required; slug to associate with field
      - name: icd_diagnoses
        type: list
        description: Optional; list of ICD diagnosis codes defining a given condition
      - name: excluded_icd_diagnoses
        type: list
        description: Optional; list of ICD diagnosis codes to be excluded
      - name: procedure_codes
        type: list
        description: Optional; list of procedure codes defining a given condition
      - name: excluded_snomed_codes
        type: list
        description: Optional; list of snomed codes to be excluded
      - name: value_set_name
        type: string
        description: Optional; name of HEDIS value set defining given condition
      - name: period
        type: string
        description: Optional; filters results to within the selected time period (defaults to 1 year)
      - name: period_op
        type: string
        description: Optional; can be > or < or =
      - name: calendar_year
        type: boolean
        description: Optional; if true, the results are filtered to those with a serviceDateFrom within the calendar year
      - name: any_encounter
        type: boolean
        description: Optional; if true, the encounterType is not limited to inpatient, other, or ed
      - name: min_any_encounter_claims
        type: integer
        description: Optional; sets the number of any encounter claims (defaults to 1)
      - name: min_inpatient_claims
        type: integer
        description: Optional; sets the number of inpatient claims (defaults to 1)
      - name: min_acute_facility_claims
        type: integer
        description: Optional; sets the number of acute facility claims (defaults to 1)
      - name: min_other_claims
        type: integer
        description: Optional; sets the number of other and ed claims (defaults to 2)

  - name: encounter_evidence
    description: Produces value of 'true' for members with 1 (or more as determined by min_day_count) emergency visits or unplanned admits
    arguments:
      - name: slug
        type: string
        description: Required; slug to associate with field
      - name: ed_visits
        type: string
        description: Optional; when set to 'true' will filter by 'ed is true' in abs_encounters
      - name: unplanned_admits
        type: string
        description: Optional; when set to 'true' will filter by 'resultsInInpatient is true' in abs_encounters
      - name: min_day_count
        type: integer
        description: Optional; sets the minimum number of distinct encounters (defaults to 1)

  - name: medication_evidence
    description: >
      Produces value of 'true' for members with pharmacy claims matching provided HEDIS medication list, NDC codes,
      or lowercase ingredient names
    arguments:
      - name: slug
        type: string
        description: Required; slug to associate with field
      - name: hedis_medication_list
        type: list
        description: Optional; name of HEDIS medication list(s) defining given condition
      - name: ingredients
        type: list
        description: Optional; name of ingredient(s) that are the components of a medication
      - name: ndc_codes
        type: list
        description: Optional; list of NDC codes (string) to identify a specific medication by the labeler, product, and commercial package size
      - name: min_ndc_fill_count
        type: integer
        description: Optional; sets the number of distinct fill counts (defaults to 1)
      - name: period
        type: string
        description: Optional; filters results to within the selected time period (defaults to 1 year)
      - name: period_op
        type: string
        description: Optional; can be > or < or =
      - name: min_field
        type: string
        description: Optional; the column to filter the HAVING clause by (defaults to dateFilled)
      - name: min_field_value
        type: integer
        description: Optional; the distinct count used in the HAVING clause (defaults to 1)

  - name: member_evidence
    description: >
      Produces value of 'true' for members filtered by either member_field or age but not both
    arguments:
      - name: slug
        type: string
        description: Required; slug to associate with field
      - name: min_age
        type: integer
        description: Optional; member's minimum age
      - name: max_age
        type: integer
        description: Optional; member's maximum age
      - name: member_field
        type: string
        description: Optional; member field in member_info_table to search over on e.g., gender
      - name: member_values
        type: string
        description: Optional; member values in member_field to filter on e.g., `female`
