version: 2
models:

  - name: abs_facility_flat
    description: "\n
    Author: Mina Yi\n
    Purpose: Unnested facility claims structure for things including Looker self-service explore, abstractions, and complex queries
    "
    tests:
      - unique:
          column_name: "concat(claimId, lineId)"
          severity: warn
    columns:
      - name: claimId
        description: Global identifier for claim
        tests:
          - not_null
      - name: commonId
        description: Global identifier for all members ingested by Cityblock. Unique across silver and gold
      - name: partnerMemberId
        description: Member ID as dictated by the partner
        tests:
          - not_null
      - name: patientId
        description: Global identifier for members in a Cityblock cohort (shared with Commons)
        tests:
          - dbt_utils.at_least_one
      - name: partner
        description: Name of claim source (could differ in future for same payer different markets)
        tests:
          - not_null
      - name: partnerClaimId
        description: Claim ID as dictated by the partner
        tests:
          - not_null
      - name: lineOfBusiness
        description: Line of business - higher level categorization of product/market segment that is associated with a member's benefit package
        tests:
          - dbt_utils.at_least_one
      - name: subLineOfBusiness
        description: Sub-line of business - secondary or more granular categorization of product/market segment that is associated with a member's benefit package
        tests:
          - dbt_utils.at_least_one
      - name: typeOfBill
        description: Standard bill type providing information about the servicing provider
        tests:
          - dbt_utils.at_least_one
      - name: admitType
        description: Standard admission type code
        tests:
          - dbt_utils.at_least_one
      - name: admitSource
        description: Standard admission source code
        tests:
          - dbt_utils.at_least_one
      - name: dischargeStatus
        description: Standard discharge status code
        tests:
          - dbt_utils.at_least_one
      - name: drgVersion
        description: Version of the DRG
      - name: drgCodeset
        description: DRG system used. There are currently three major systems - Medicare-Severity, All-Patient and All-Patient Refined
        tests:
          - dbt_utils.at_least_one
      - name: drgCode
        description: Diagnostic-related group - a classification system that measures resource intensity of an inpatient stay.
        tests:
          - dbt_utils.at_least_one
      - name: providerBillingId
        description: Global identifier for billing provider
        tests:
          - dbt_utils.at_least_one:
              severity: warn
      - name: providerBillingSpecialty
        description: CMS Medicare specialty code for billing provider
        tests:
          - dbt_utils.at_least_one:
              severity: warn
      - name: providerReferringId
        description: Global identifier for referring provider
      - name: providerReferringSpecialty
        description: CMS Medicare specialty code for referring provider
      - name: providerServicingId
        description: Global identifier for servicing/rendering provider
        tests:
          - dbt_utils.at_least_one
      - name: providerServicingSpecialty
        description: CMS Medicare specialty code for servicing/rendering provider
        tests:
          - dbt_utils.at_least_one
      - name: providerOperatingId
        description: Global identifier for operating provider
      - name: providerOperatingSpecialty
        description: CMS Medicare specialty code for operating provider
      - name: lineNumber
        description: Service line number
        tests:
          - not_null
      - name: lineId
        description: Claim line-level identifier
        tests:
          - not_null
      - name: COBFlag
        description: Boolean indicator of payments from secondary payers
      - name: capitatedFlag
        description: Line is part of a capitated payment (typically constant for each line on a facility claim)
      - name: claimLineStatus
        description: Payment status of the claim line.
        tests:
          - dbt_utils.at_least_one:
              severity: warn
      - name: inNetworkFlag
        description: Network status of servicing provider
      - name: serviceQuantity
        description: Count of service rendered
        tests:
          - dbt_utils.at_least_one:
              severity: warn
      - name: typesOfService.tier
        description: Tier of categorisation of service rendered
      - name: typesOfService.code
        description: Categorisation of service rendered
      - name: revenueCode
        description: Standard revenue code (only on facility claims and at the line-level)
      - name: dateFrom
        description: Service start date of the claimline
        tests:
          - not_null
      - name: dateTo
        description: Service end date of the claimline
        tests:
          - not_null
      - name: datePaid
        description: Paid date of the claimline
        tests:
          - dbt_utils.at_least_one
      - name: dateAdmit
        description: Admission date
        tests:
          - dbt_utils.at_least_one
      - name: dateDischarge
        description: Discharge date
        tests:
          - dbt_utils.at_least_one
      - name: amountAllowed
        description: The negotiated amount the provider receives
        tests:
          - not_null
      - name: amountBilled
        description: The amount the provider bills the insurer
        tests:
          - dbt_utils.at_least_one
      - name: amountCOB
        description: The amount a prior payer has paid (e.g. dual medical coverage, workers comp)
      - name: amountCopay
        description: Member liable amount - Fixed amount per visit (e.g. office visits, ED visits, prescription drugs)
      - name: amountDeductible
        description: Member liable amount - Amount applied to deductible
      - name: amountCoinsurance
        description: Member liable amount - Amount the member pays once the deductible has been reached
      - name: amountPlanPaid
        description: The amount for which the payer is responsible
        tests:
          - not_null
      - name: procedureCode
        description: Standard CPT/HCPCS service code
        tests:
          - dbt_utils.at_least_one
      - name: procedureModifier1
        description: CPT modifier codes (professional and outpatient facility claims only)
        tests:
          - dbt_utils.at_least_one
      - name: procedureModifier2
        description: CPT modifier codes (professional and outpatient facility claims only)
      - name: principalDiagnosisCode
        description: Standard ICD diagnosis code that is primarily responsible for the admission of the patient to the hospital for care during the hospitalization
        tests:
          - dbt_utils.at_least_one
      - name: principalProcedureCode
        description: Standard ICD procedure code performed for definitive treatment rather than for diagnostic or exploratory purposes, or which is necessary to take care of a complication
        tests:
          - dbt_utils.at_least_one
      - name: surrogateId
        description: ID corresponding to identifier.surrogateId in silver
        tests:
          - not_null
      - name: surrogateProject
        description: BigQuery project that hosts silver claims
        tests:
          - not_null
      - name: surrogateDataset
        description: BigQuery dataset that hosts silver claims
        tests:
          - not_null
      - name: surrogateTable
        description: BigQuery table that hosts silver claims
        tests:
          - not_null

  - name: abs_pharmacy_flat
    description: Flatten gold pharmacy tables to support self-service
    tests:
      - unique:
          column_name: "concat(claimId, fillNumber)"
          severity: warn

  - name: abs_professional_flat
    description: Flatten gold professional tables to support self-service
    tests:
      - unique:
          column_name: "concat(claimId, lineId)"
          severity: warn
