version: 2

sources:
  - name: snapshots
    description: Historical SCD Type 2 Data Snapshotted Using DBT
    database: cityblock-analytics
    schema: snapshots

    tables:
      - name: user_snapshot