
# the medical data source

version: 2

sources:

  - name: payer_encounters
    description: Derived encounters from partner claims
    database: cityblock-data
    schema: abstractions

    tables:
      - name: cci_encounters
      - name: emblem_encounters

  - name: medical
    description: Set of medical tables created by mixer
    database: cityblock-data
    schema: medical

    tables:
      - name: patient_encounters
      - name: patient_hie_events
      - name: patient_medications
      - name: patient_orders
      - name: patient_problems
      - name: patient_results
      - name: patient_vital_signs


  - name: streaming
    description: Set of tables for raw streaming data
    database: cityblock-data
    schema: streaming

    tables:
      - name: redox_messages

  - name: elation
    description: elation tables mirrored to bigquery
    database: cbh-db-mirror-prod
    schema: elation_mirror

    tables:
      - name: appointment_latest
      - name: med_order_latest
      - name: referral_order_latest
      - name: user_latest
      - name: appointment_status_latest

  - name: medical_uploads
    description: static tables/spreadsheets with manual/backfill data
    database: cityblock-analytics
    schema: uploads

    tables:
      - name: epic_apv_backfill
