
version: 2

sources:

  - name: evaluation
    description: Google Sheet imports for evaluation
    database: cityblock-analytics
    schema: evaluation

    tables:
      - name: panel_capacity_chp_exclusions
      - name: panel_capacity_chp_status
      - name: patient_comorbidities
