version: 2

models:
  - name: patient_encounters
    description: "Originally transformed from patient_encounters. Holds info related to member medical encounters/visits."
    tests:
      - equal_rowcount:
          compare_model: source('medical', 'patient_encounters')
      - encounter_transform_equality:
          compare_model: source('medical', 'patient_encounters')

  - name: latest_patient_encounters
    description: "Author - Kola Awe\nPurpose - Partitions the patient_encounters table on patientId and
                  orders rows by messageId (DESC) to generate view of most recent/current state of patient
                  encounters per patient.\nDependencies - staging-cityblock-data.dev_medical.patient_encounters"

    tests:
      - encounter_transform_equality:
            compare_model: source('medical', 'latest_patient_encounters')
      - encounter_transform_view_unique
