package cityblock.models.connecticare.silver

import com.spotify.scio.bigquery.types.BigQueryType

object AttributedPCP {
  @BigQueryType.toTable
  case class ParsedAttributedPCP(
    RecordType: Option[String],
    Source_System_ID: Option[String],
    Group_Level_1_ID: Option[String],
    Group_Level_2_ID: Option[String],
    Group_Level_3_ID: Option[String],
    Subscriber_ID: Option[String],
    Member_ID: String,
    Member_Suffix: Option[String],
    Type: Option[String],
    Provider_ID: Option[String],
    Provider_Num: Option[String],
    Provider_Location: Option[String],
    Primary_Care_Provider_Type: Option[String],
    Provider_Name: Option[String],
    Primary_Care_Provider_Effective_Date: Option[String],
    Primary_Care_Provider_Termination_Date: Option[String],
    Primary_Care_Provider_Termination_Reason: Option[String],
    National_Practitioner_Identifier: Option[String],
    Provider_Tax_Identification_Number: Option[String],
    Network_Group_Identifier: Option[String],
    Medical_Center_ID: Option[String],
    Capitation_Indicator: Option[String],
    Service_Area_Code: Option[String],
    Tier_Benefit_Indicator: Option[String],
    Provider_record_creation_datetime: Option[String],
    Custom_ID_1: Option[String],
    Custom_Val_1: Option[String],
    Custom_Desc_1: Option[String],
    Custom_ID_2: Option[String],
    Custom_Val_2: Option[String],
    Custom_Desc_2: Option[String],
    Custom_ID_3: Option[String],
    Custom_Val_3: Option[String],
    Custom_Desc_3: Option[String],
    Custom_ID_4: Option[String],
    Custom_Val_4: Option[String],
    Custom_Desc_4: Option[String],
    Custom_ID_5: Option[String],
    Custom_Val_5: Option[String],
    Custom_Desc_5: Option[String],
    Custom_ID_6: Option[String],
    Custom_Val_6: Option[String],
    Custom_Desc_6: Option[String],
    Custom_ID_7: Option[String],
    Custom_Val_7: Option[String],
    Custom_Desc_7: Option[String],
    Custom_ID_8: Option[String],
    Custom_Val_8: Option[String],
    Custom_Desc_8: Option[String],
    _50: Option[String]
  )
}
