package cityblock.models.connecticare.silver

import com.spotify.scio.bigquery.types.BigQueryType
import org.joda.time.LocalDate

object FacetsMedical {
  @BigQueryType.toTable
  case class ParsedFacetsMedical(
    EXT_4332_LOB: Option[String],
    EXT_1208_ICD9_DIAG_CODE1: Option[String],
    EXT_1208_ICD9_DIAG_CODE2: Option[String],
    EXT_1208_ICD9_DIAG_CODE3: Option[String],
    EXT_1208_ICD9_DIAG_CODE4: Option[String],
    EXT_1208_ICD9_DIAG_CODE5: Option[String],
    EXT_1208_ICD9_DIAG_CODE6: Option[String],
    EXT_1208_ICD9_DIAG_CODE7: Option[String],
    EXT_1208_ICD9_DIAG_CODE8: Option[String],
    EXT_1208_ICD9_DIAG_CODE9: Option[String],
    EXT_1208_ICD9_DIAG_CODE10: Option[String],
    EXT_1208_ICD9_DIAG_CODE11: Option[String],
    EXT_1208_ICD9_DIAG_CODE12: Option[String],
    EXT_1216_PRIN_DIAG_CODE: Option[String],
    EXT_1207_PLACE_OF_SERVICE: Option[String],
    EXT_1219_PROC_MODIFY: Option[String],
    EXT_2712_PROV_SPECIALTY: Option[String],
    EXT_UNITS_N_1: Option[String],
    EXT_1206_TYPE_OF_SERVICE: Option[String],
    EXT_PAR_IND: Option[String],
    EXT_PAYMT_STATUS_1: Option[String],
    EXT_PAID_AMT_1: Option[String],
    COINSURANCE: Option[String],
    DEDUCTIBLE: Option[String],
    COPAY: Option[String],
    EXT_BILLED_AMT_1: Option[String],
    EXT_ALLOWED_AMOUNT_1: Option[String],
    EXT_END_DOS: Option[LocalDate],
    EXT_BEG_DOS: Option[LocalDate],
    EXT_1001_CLAIM_NUMBER: String,
    ICD_INDICATOR: Option[String],
    EXT_2001_PROVIDER_ID: Option[String],
    EXT_1218_PROC_CODE: Option[String],
    EXT_1700_BILL_TYPE: Option[String],
    EXT_1714_REVENUE_CODE1: Option[String],
    EXT_FFS_OR_CAP_IND_1: Option[String],
    EXT_1531_ADMIT_TYPE: Option[String],
    EXT_1721_ADMIT_SOURCE: Option[String],
    EXT_1704_DISCHARGE_STATUS: Option[String],
    EXT_1503_ADMIT_DT: Option[LocalDate],
    EXT_DISCHARGE_DT: Option[LocalDate],
    EXT_1506_PRIN_PROC_CODE: Option[String],
    EXT_1506_ICD9_PROC_CODE1: Option[String],
    EXT_1506_ICD9_PROC_CODE2: Option[String],
    EXT_1506_ICD9_PROC_CODE3: Option[String],
    EXT_1506_ICD9_PROC_CODE4: Option[String],
    EXT_1506_ICD9_PROC_CODE5: Option[String],
    EXT_1506_ICD9_PROC_CODE6: Option[String],
    EXT_1506_ICD9_PROC_CODE7: Option[String],
    EXT_1506_ICD9_PROC_CODE8: Option[String],
    EXT_1506_ICD9_PROC_CODE9: Option[String],
    EXT_1506_ICD9_PROC_CODE10: Option[String],
    EXT_1506_ICD9_PROC_CODE11: Option[String],
    EXT_1506_ICD9_PROC_CODE12: Option[String],
    EXT_1653_DRG: Option[String],
    EXT_PAYMT_DATE_1: Option[String],
    EXT_PAYMT_DATE_2: Option[String]
  )
}
