package cityblock.models.connecticare.silver

import com.spotify.scio.bigquery.types.BigQueryType

object HealthCoverageBenefits {
  @BigQueryType.toTable
  case class ParsedHealthCoverageBenefits(
    RecordType: Option[String],
    Source_System_ID: Option[String],
    Group_Level_1_ID: Option[String],
    Group_Level_2_ID: Option[String],
    Group_Level_3_ID: Option[String],
    Subscriber_ID: Option[String],
    Member_ID: String,
    Member_Suffix: Option[String],
    Type: Option[String],
    Benefit_Category: Option[String],
    Embedded_Dental_Indicator: Option[String],
    Embedded_Vision_Indicator: Option[String],
    Embedded_Mental_Health_Indicator: Option[String],
    Embedded_Pharmacy_Indicator: Option[String],
    Benefit_ID: Option[String],
    Product_Identifier: Option[String],
    Family_Indicator: Option[String],
    Eligibility_Type: Option[String],
    Eligibility_Reason: Option[String],
    Coverage_effective_date: Option[String],
    Coverage_termination_date: Option[String],
    Calendar_or_Contract_Year_Indicator: Option[String],
    Eligibility_process_create_timestamp: Option[String],
    Line_of_Business: Option[String],
    Benefit_Description: Option[String],
    Product_Description: Option[String],
    Employer_Group_Type: Option[String],
    Benefit_Option: Option[String],
    Custom_ID_1: Option[String],
    Custom_Val_1: Option[String],
    Custom_Desc_1: Option[String],
    Custom_ID_2: Option[String],
    Custom_Val_2: Option[String],
    Custom_Desc_2: Option[String],
    Custom_ID_3: Option[String],
    Custom_Val_3: Option[String],
    Custom_Desc_3: Option[String],
    Custom_ID_4: Option[String],
    Custom_Val_4: Option[String],
    Custom_Desc_4: Option[String],
    Custom_ID_5: Option[String],
    Custom_Val_5: Option[String],
    Custom_Desc_5: Option[String],
    Custom_ID_6: Option[String],
    Custom_Val_6: Option[String],
    Custom_Desc_6: Option[String],
    Custom_ID_7: Option[String],
    Custom_Val_7: Option[String],
    Custom_Desc_7: Option[String],
    Custom_ID_8: Option[String],
    Custom_Val_8: Option[String],
    Custom_Desc_8: Option[String],
    _53: Option[String]
  )
}
