package cityblock.models.connecticare.silver

import com.spotify.scio.bigquery.types.BigQueryType
import org.joda.time.LocalDate

object Medical {
  @BigQueryType.toTable
  case class ParsedMedical(
    Partnership_Current: Option[String],
    NMI: String,
    NMI_Sub: Option[String],
    LOB1: Option[String],
    LOB2: Option[String],
    Age: Option[String],
    Gender: Option[String],
    GrpNum: Option[String],
    DivNum: Option[String],
    BenPack: Option[String],
    COCLevel1: Option[String],
    COCLevel2: Option[String],
    ClmNum: String,
    ClmServNum: String,
    ClaimType: Option[String],
    PCP_Num: Option[String],
    PCP_AffNum: Option[String],
    PCP_NPI: Option[String],
    PCP_TIN: Option[String],
    ServProvNum: Option[String],
    ServProvAffNum: Option[String],
    ServProvNPI: Option[String],
    ServProvTIN: Option[String],
    ServProvSpec1: Option[String],
    ServProvClass: Option[String],
    ServProvCat: Option[String],
    RefProvNum: Option[String],
    RefProvAffNum: Option[String],
    RefProvNPI: Option[String],
    RefProvTIN: Option[String],
    DateEff: Option[LocalDate],
    DateEnd: Option[LocalDate],
    DateAdmit: Option[LocalDate],
    DateDischarge: Option[LocalDate],
    DatePaid: Option[LocalDate],
    Proc1: Option[String],
    Proc1Type: Option[String],
    Location: Option[String],
    Modifer1: Option[String],
    Modifier2: Option[String],
    DRG: Option[String],
    MDC: Option[String],
    AdmitType: Option[String],
    DischargeStatus: Option[String],
    PaymentStatus_NetworkInOut: Option[String],
    ERAvoid_Flag: Option[String],
    InptFac_Acute_SubAcute: Option[String],
    Qty: Option[String],
    Days: Option[String],
    AmtCharge: Option[String],
    AmtAllow: Option[String],
    AmtCoins: Option[String],
    AmtCopay: Option[String],
    AmtDeduct: Option[String],
    AmtPay: Option[String],
    Explain1: Option[String],
    Explain2: Option[String],
    Proc2: Option[String],
    Proc2Type: Option[String],
    BillTypeCd: Option[String],
    CareCentrix: Option[String]
  )
}
