
version: 2

sources:

  - name: member_index
    description: The member_index schema is the source of truth for core member information
    database: cbh-db-mirror-prod
    schema: member_index_mirror

    tables:
      - name: category
      - name: cohort
      - name: datasource
      - name: email
      - name: member
      - name: member_datasource_identifier
        identifier: member_insurance
      - name: member_demographics
      - name: member_insurance_details
      - name: mrn
      - name: partner
      - name: phone
