version: 2

models:
  - name: abs_emblem_member_medical_center
    description: "\n
    Author:  Andy Seiden\n
    Purpose: Identify most recent medical center by member\n
    "
    columns:
      - name: patientId
        tests:
          - not_null
          - unique
      - name: emblemMedicalCenterName
        tests:
          - not_null
          
  - name: emblem_provider_organization
    description: "\n
    Author:  Katie Claiborne\n
    Purpose: Identify Emblem provider affiliations based on most recent billing ID\n
    "
    columns:
      - name: providerId
        tests: 
          - unique
      - name: providerNpi
        tests:
          - not_null
      - name: providerName
      - name: providerOrganization

  - name: primary_care_assignment
    description: "\n
    Author: Katie Claiborne\n
    Purpose: Identify member primary care physicians by month"

  - name: fuzzy_crosswalk
    description: "\n
    Author: Andy Seiden\n
    Purpose: Crosswalk of patientIds to emblem MEMBERIDs, only for cases that are missing from the current the patient_index_cache. This is created in python manually on a monthly basis after we receive new emblem data. Note this is not a full listing of all patientIds and externalIds."
  
  - name: master_member_base_cardinal
    description: "\n
    Author: Andy Seiden\n
    Purpose: WARNING: DO NOT USE THIS TABLE. cardinal master member table (v1 silver). Interim step feeding master_member_v1. Concatenates carefirst membership sharded tables together, and consolidates with islands logic."
  
  - name: master_member_cardinal
    description: "\n
    Author: Andy Seiden\n
    Purpose: WARNING: DO NOT USE THIS TABLE. cardinal master member table (v1 silver). Interim step feeding master_member_v1. Concatenates carefirst membership sharded tables together, and consolidates with islands logic."
  
  - name: master_member_base_carefirst
    description: "\n
    Author: Andy Seiden\n
    Purpose: WARNING: DO NOT USE THIS TABLE. Carefirst master member table (v1 silver). Interim step feeding master_member_v1. Concatenates carefirst membership sharded tables together, and consolidates with islands logic."
  
  - name: master_member_carefirst
    description: "\n
    Author: Andy Seiden\n
    Purpose: WARNING: DO NOT USE THIS TABLE. Carefirst master member table (v1 silver). Interim step feeding master_member_v1. Concatenates carefirst membership sharded tables together, and consolidates with islands logic."
  
  - name: master_member_base_cci
    description: "\n
    Author: Andy Seiden\n
    Purpose: WARNING: DO NOT USE THIS TABLE. Connecticare master member table (v1 silver). Interim step feeding master_member_v1. Concatenates cci membership sharded tables together, and consolidates with islands logic. Code adapted from emblem master member."

  - name: master_member_base_cci_amysis
    description: "\n
    Author: Andy Seiden\n
    Purpose: WARNING: DO NOT USE THIS TABLE. Connecticare master member table (v1 silver). Interim step feeding master_member_v1. Concatenates cci membership sharded tables together, and consolidates with islands logic. Code adapted from emblem master member."
 
  - name: master_member_base_cci_facets
    description: "\n
    Author: Andy Seiden\n
    Purpose: WARNING: DO NOT USE THIS TABLE. Connecticare master member table (v1 silver). Interim step feeding master_member_v1. Concatenates cci membership sharded tables together, and consolidates with islands logic. Code adapted from emblem master member."
 
  - name: master_member_cci
    description: "\n
    Author: Andy Seiden\n
    Purpose: WARNING: DO NOT USE THIS TABLE. Applies islands logic to master_member_cci_base for grouping and consolidating duplicate member-month records across multiple consecutive partner data-shipments."
  
  - name: master_member_dc_historic
    description: "\n
    Author: Andy Seiden\n
    Purpose: WARNING: DO NOT USE THIS TABLE. Carefirst dc district historic claims DERIVED eligibility for member month spine for claims self service denominators, assuming having a claim in a given calendar quarter indicates eligibility for that quarter."
  
  - name: master_member_base_emblem_no_row_num
    description: "\n
    Author: Andy Seiden\n
    Purpose: WARNING: DO NOT USE THIS TABLE. Emblem master member table (v1 silver). Interim step feeding master_member_v1. Concatenates emblem membership sharded tables together, and consolidates with islands logic."
     
  - name: master_member_base_emblem
    description: "\n
    Author: Andy Seiden\n
    Purpose: WARNING: DO NOT USE THIS TABLE. This interim table only adds rowNum to the prior table. Emblem master member table (v1 silver). Interim step feeding master_member_v1. Concatenates emblem membership sharded tables together, and consolidates with islands logic."
  
  - name: master_member_emblem
    description: "\n
    Author: Andy Seiden\n
    Purpose: WARNING: DO NOT USE THIS TABLE. Applies islands logic to master_member_emblem_base for grouping and consolidating duplicate member-month records across multiple consecutive partner data-shipments."

  - name: master_member_emblem_compressed
    description: "Shaping data so each row represents a continuous period of enrollment for a member\n
    Author: Gerardo Sierra\n
    Purpose: Allows to quickly identify enrollment periods for members, and understand whether there are gaps in eligibility. Used for risk modeling as well\n" 
 
  - name: master_member_base_healthy_blue
    description: "\n
    Author: Andy Seiden\n
    Purpose: WARNING: DO NOT USE THIS TABLE. healthyblue master member table (v1 silver). Interim step feeding master_member_v1. Concatenates healthyblue membership sharded tables together, and consolidates with islands logic."
  
  - name: master_member_healthy_blue
    description: "\n
    Author: Andy Seiden\n
    Purpose: WARNING: DO NOT USE THIS TABLE. healthyblue master member table (v1 silver). Interim step feeding master_member_v1. Concatenates healthyblue membership sharded tables together, and consolidates with islands logic."
  
  - name: master_member_healthy_blue_historic
    description: "\n
    Author: Andy Seiden\n
    Purpose: WARNING: DO NOT USE THIS TABLE. healthy_blue historic claims DERIVED eligibility for member month spine for claims self service denominators, assuming having a claim in a given calendar quarter indicates eligibility for that quarter."
  
  - name: master_member_mass_health
    description: "\n
    Author: Andy Seiden\n
    Purpose: WARNING: DO NOT USE THIS TABLE. Tufts Mass Health historic claims DERIVED eligibility for member month spine for claims self service denominators, assuming having a claim in a given calendar quarter indicates eligibility for that quarter."
  
  - name: master_member_prep_data
    description: "\n
    Author: Andy Seiden\n
    Purpose: WARNING: DO NOT USE THIS TABLE. This is a temporary staging table between payer data and master_member_v1, to clean and reshape data from multiple sources, and to avoid reource allocation errors in bigquery."
  
  - name: master_member_prep_data_uuid
    description: "\n
    Author: Andy Seiden\n
    Purpose: WARNING: DO NOT USE THIS TABLE. This is a temporary staging table between payer data and master_member_v1, to clean and reshape data from multiple sources, and to avoid reource allocation errors in bigquery."

  - name: master_member_prep_data_unsorted
    description: "\n
    Author: Andy Seiden\n
    Purpose: WARNING: DO NOT USE THIS TABLE. This is a temporary staging table between payer data and master_member_v1, to clean and reshape data from multiple sources, and to avoid reource allocation errors in bigquery."

  - name: master_member_prep_data_unsorted2
    description: "\n
    Author: Andy Seiden\n
    Purpose: WARNING: DO NOT USE THIS TABLE. This is a temporary staging table between payer data and master_member_v1, to clean and reshape data from multiple sources, and to avoid reource allocation errors in bigquery."
