version: 2

models:
  - name: thpp_regulatory_maternity
    description: "title: tufts maternity weekly regulatory data supplement |
    author: nabig chaudhry |
    runtime: daily"

  - name: thpp_new_member_universe
    description: "title: tufts new member universe monthly report for audit purpose |
    author: alankrita ghosh"
    columns:
      - name: memberId
        tests:
          - unique
          - not_null
      - name: isHardToReachAssessment
        tests:
          - accepted_values:
              values: ['HTRAssessment', ' ']
      - name: isHardToReachCarePlanning
        tests:
          - accepted_values:
              values: ['HTRCarePlanning', ' ']
      - name: refusalAssessment
        tests:
          - accepted_values:
              values: ['refusalAssessment', ' ' ]
      - name: refusalCarePlan
        tests:
          - accepted_values:
              values: [ 'refusalCarePlan', ' ' ]

  - name: thpp_regulatory_commons_monthly
    description: Tufts Commons monthly regulatory data supplement
    columns:
      - name: MemberID
        tests:
          - unique
      - name: HTRStatus_CarePlanning
        tests:
          - accepted_values:
              values: ['Y', 'N']
          - not_null

  - name: cm_consented_member_info
    description: "title: care management consented member info |
    author: nabig chaudhry |
    runtime: daily"

  - name: cm_internal_summary
    description: "title: care management internal summary report |
    author: nabig chaudhry |
    runtime: daily"
    columns:
      - name: patientId
        tests:
          - not_null
      - name: fullName
      - name: dateOfBirth
      - name: primaryCommunityHealthPartnerName
      - name: currentState
        description: "Member's current status"
        tests:
          - not_null
          - accepted_values:
              values: ['consented', 'enrolled']
      - name: consentedAt
      - name: consentedToCurrentDays
      - name: mapInitiatedAt
        description: "Member action plan intiation date"
      - name: consentedToMapDays
        description: "Days between member action plan intiation date and consent date"
      - name: baselineAssessmentInitiatedAt
      - name: baselineAssessmentCompletedAt
      - name: consentedToBaselineAssessmentDays
      - name: baselineCompletedWithin60Days
        tests:
          - accepted_values:
              values: ['Yes', 'No', 'N/A']
      - name: memberImpressionsCompleted
        description: "Member's impressions field in Commons completed status"
        tests:
          - accepted_values:
              values: ['Yes', 'No', 'N/A']
      - name: mapIntiatedWithin30DaysOfConsent
        tests:
          - accepted_values:
              values: ['Yes', 'No', 'N/A']
      - name: totalGoalsCompleted
      - name: intialCaseConferenceAt
      - name: daysSinceLastCaseConference
      - name: quarterlyCaseConferenceConducted
        tests:
          - accepted_values:
              values: ['Yes', 'No', 'N/A']
      - name: initialMemberAcuityDescription
      - name: currentMemberAcuityDescription
      - name: month
      - name: tendsPerMonth
      - name: minimumTendsMetForCurrentAcuity
        description: "Member has received the minimum required number of tends for their given acuity"
        tests:
          - accepted_values:
              values: ['Yes', 'No', 'N/A']
      - name: appropriateTendsForCurrentAcuity
        description: "Member has received an appropriate amount of tends (not too high or too low) for their given acuity"
        tests:
          - accepted_values:
              values: ['N/A', 'High - Consider Status Change', 'Appropriate', 'Low - Inappropriate']

