version: 2

models:
  - name: mrt_cotiviti_historical_individual_risk_drivers
    description: Historical Cotiviti output giving the top 5 factors driving a member's model prediction, for a subset of members (top 5% highest score), for certain models.
    columns:
      - name: id
        description: Unique identifier based on a hash of the output predictions id and the rank of the individual risk driver
        tests:
          - unique
          - not_null
      - name: cotivitiPredictionId
        description: Primary key of the `mrt_cotiviti_historical_output_predictions` model
        tests:
          - not_null
      - name: patientId
        tests:
          - not_null
      - name: runId
        tests:
          - not_null
      - name: reportId
        tests:
          - not_null
      - name: modelId
        tests:
          - not_null
      - name: ModelBasePeriodStart
        tests:
          - not_null
      - name: ModelBasePeriodEnd
        tests:
          - not_null
      - name: rank
        tests:
          - not_null
          - accepted_values:
              values: [1, 2, 3, 4, 5]
              quote: false
      - name: clinicalConditionCategory
        description: Code and description of the risk driver
        tests:
          - not_null
      - name: riskContributionPercent
        description: Percentage of the member's prediction score explained by the risk driver
        tests:
          - not_null
      - name: createdAt
        tests:
          - not_null

  - name: mrt_cotiviti_historical_likelihood_of_hospitalization
    description: Historical Cotiviti prediction of the likelihood of being hospitalized within the next 6 months after the model base period
    columns:
      - name: id
        description: Unique identifier based on hash of `patientId`, `modelId`, `ModelBasePeriodStart` and `ModelBasePeriodEnd`, defined in the `abs_cotiviti_member_selected_historical_runs` model
        tests:
          - unique
          - not_null
      - name: patientId
      - name: modelId
      - name: runId
      - name: predictedLikelihoodOfHospitalization
      - name: modelName
      - name: ModelBasePeriodStart
      - name: ModelBasePeriodEnd
      - name: createdAt

  - name: mrt_cotiviti_historical_predicted_expenditures_concurrent_prospective_delta
    description: "Ranks members by market and expenditure type according to projected and current expenditure as well as the delta between them.\n
       Note that not some members, depending on their LOB, may be missing predictions of certain expenditure types. For example, currently we have no\n
       model to predict medical expenditures for Medicaid members. For an overview of models available by LOB, consult `cityblock-analytics.src_cotiviti.model_info`."
    columns:
      - name: patientId
        tests:
          - not_null
      - name: patientHomeMarketName
        tests:
          - not_null
      - name: ModelBasePeriodStart
        tests:
          - not_null
      - name: ModelBasePeriodEnd
        tests:
          - not_null
      - name: modelTargetPopulation
        tests:
          - not_null
      - name: expenditureType
        tests:
          - not_null
      - name: prospectiveModelId
        tests:
          - not_null
      - name: prospectivePredictionId
        description: Identifier of the prospective risk prediction, defined in `abs_cotiviti_member_selected_historical_runs`
      - name: concurrentModelId
      - name: concurrentPredictionId
        description: Identifier of the of the concurrent risk prediction, defined in `abs_cotiviti_member_selected_historical_runs`
      - name: prospectiveExpectedCostPMPM
        description: Predicted average medical expenses per month for the 12 months after the base period
        tests:
          - not_null
      - name: concurrentExpectedCostPMPM
        description: Predicted average medical expenses per month during the base period
      - name: prospectiveConcurrentCostDeltaPMPM
        description: Prospective cost PMPM - Concurrent cost PMPM
      - name: prospectiveCostPercentRank
        description: Percent rank in descending order of prospective medical cost by market and model base period
        tests:
          - not_null
      - name: concurrentCostPercentRank
        description: Percent rank in descending order of concurrent medical cost by market and model base period
      - name: prospectiveConcurrentCostDeltaPercentRank
        description: Percent rank in descending order of the delta between prospective and concurrent medical cost by market and model base period

  - name: mrt_cotiviti_latest_individual_risk_drivers
    description: Latest Cotiviti output giving the top 5 factors driving a member's model prediction, for a subset of members (top 5% highest score), for certain models.
    columns:
      - name: id
        description: Unique risk driver ID, generated in the `mrt_cotiviti_historical_individual_risk_drivers` model
        tests:
          - unique
          - not_null
      - name: cotivitiPredictionId
        description: Primary key of the `mrt_cotiviti_historical_output_predictions` model
        tests:
          - not_null
      - name: patientId
        tests:
          - not_null
      - name: runId
        tests:
          - not_null
      - name: reportId
        tests:
          - not_null
      - name: modelId
        tests:
          - not_null
      - name: ModelBasePeriodStart
        tests:
          - not_null
      - name: ModelBasePeriodEnd
        tests:
          - not_null
      - name: rank
        tests:
          - not_null
          - accepted_values:
              values: [1, 2, 3, 4, 5]
              quote: false
      - name: clinicalConditionCategory
        description: Code and description of the risk driver
        tests:
          - not_null
      - name: riskContributionPercent
        description: Percentage of the member's prediction score explained by the risk driver
        tests:
          - not_null
      - name: createdAt
        tests:
          - not_null

  - name: mrt_cotiviti_latest_likelihood_of_hospitalization
    description: Latest Cotiviti prediction of the likelihood of being hospitalized within the next 6 months
    columns:
      - name: id
      - name: patientId
      - name: modelId
      - name: runId
      - name: predictedLikelihoodOfHospitalization
      - name: modelName
      - name: ModelBasePeriodStart
      - name: ModelBasePeriodEnd
      - name: createdAt
        tests:
          - not_null

  - name: mrt_cotiviti_latest_predicted_expenditures_concurrent_prospective_delta
    description: "Ranks members by market according to projected and current expenditure as well as the delta between them.\n
       Note that not some members, depending on their LOB, may be missing predictions of certain expenditure types. For example, currently we have no\n
       model to predict medical expenditures for Medicaid members. For an overview of models available by LOB, consult `cityblock-analytics.src_cotiviti.model_info`."
    columns:
      - name: patientId
        tests:
          - not_null
      - name: patientHomeMarketName
        tests:
          - not_null
      - name: ModelBasePeriodStart
        tests:
          - not_null
      - name: ModelBasePeriodEnd
        tests:
          - not_null
      - name: modelTargetPopulation
        tests:
          - not_null
      - name: expenditureType
        tests:
          - not_null
      - name: prospectiveModelId
        tests:
          - not_null
      - name: prospectivePredictionId
        description: Identifier of the prospective risk prediction, defined in `abs_cotiviti_member_selected_historical_runs`
      - name: concurrentModelId
      - name: concurrentPredictionId
        description: Identifier of the concurrent risk prediction, defined in `abs_cotiviti_member_selected_historical_runs`
      - name: prospectiveExpectedCostPMPM
        description: Predicted average medical expenses per month for the 12 months after the base period
        tests:
          - not_null
      - name: concurrentExpectedCostPMPM
        description: Predicted average medical expenses per month during the base period
      - name: prospectiveConcurrentCostDeltaPMPM
        description: Prospective cost PMPM - Concurrent cost PMPM
      - name: prospectiveCostPercentRank
        description: Percent rank in descending order of prospective medical cost
        tests:
          - not_null
      - name: concurrentCostPercentRank
        description: Percent rank in descending order of concurrent medical cost
      - name: prospectiveConcurrentCostDeltaPercentRank
        description: Percent rank in descending order of the delta between prospective and concurrent medical cost
