version: 2

models:
  - name: abs_commons_notes
    description: Unions outreach and progress notes
    columns:
      - name: id
        tests:
          - unique
          - not_null
      - name: noteType
        tests:
          - accepted_values:
              values: ['outreach', 'progress']

  - name: stg_commons_outreach_notes
    description: Prepare outreach notes for union with progress notes
    columns:
      - name: id
        tests:
          - unique
          - not_null
      - name: groupId
      - name: patientId
      - name: userId
      - name: noteType
        tests:
          - accepted_values:
              values: ['outreach']
      - name: direction
      - name: modality
      - name: groupedModality
        description: Converts phone and in-person values to equivalent progress note strings
      - name: location
        description: Sets relevant modality values to 'Community', 'Hub', and 'Member Home'; otherwise null
      - name: status
        description: Set to 'attempt' where `personReached` is 'noOne', otherwise 'success'
        tests:
          - accepted_values:
              values: ['attempt', 'success']
      - name: isLegacy
      - name: isTransitionOfCare
        description: Set to true where `modality` contains 'careTransitions%', otherwise false
      - name: isReferral
      - name: referral
      - name: referralReason
      - name: isScheduledOutreach
      - name: outreachOutcome
      - name: outreachNotInterestedReason
      - name: interactionAt
      - name: createdAt
      - name: deletedAt
      - name: attendees
      - name: templateSlug
      - name: noteText

  - name: stg_commons_progress_notes
    description: Prepare progress notes for union with outreach notes
    columns:
      - name: id
        tests:
          - unique
          - not_null
      - name: groupId
      - name: patientId
      - name: userId
      - name: noteType
        tests:
          - accepted_values:
              values: ['progress']
      - name: direction
      - name: modality
      - name: groupedModality
      - name: location
      - name: status
      - name: isLegacy
      - name: isTransitionOfCare
      - name: isReferral
      - name: referral
      - name: referralReason
      - name: isScheduledOutreach
      - name: outreachOutcome
      - name: outreachNotInterestedReason
      - name: interactionAt
      - name: createdAt
      - name: deletedAt
      - name: attendees
      - name: templateSlug
      - name: noteText
