version: 2

models:
  - name: xpt_member_360
    description: >
      Table supporting Member 360 analysis. See project PRD for more information:
      https://docs.google.com/document/d/1zt4Hpsq7AnX29v4IE8Hiv4uJuHaDujQM1Yp4c5UeMAc
    columns:
      - name: id
        description: Unique identifier, based on `patientId`, `claimId`, `lineNumber`, and `claimLineStatus`
        tests:
          - unique
          - not_null
      - name: cohortName
        tests:
          - not_null
      - name: historicalDeliveryModel
        description: >
          Member delivery model on `dateFrom`.
          If member did not have delivery model, we assign a value of `community`.
        tests:
          - not_null
      - name: wasConsented
        description: >
          Indicates whether member state was 'consented' or 'enrolled' on `dateFrom`.
          If member did not have a state, we assign a value of 'false'.
        tests:
          - not_null
      - name: lengthOfStay
        description: >
          Derived field, based on difference between admit and discharge dates.
          Will be null for claim-lines where either date is null.
