package cityblock.models.carefirst.silver

import com.spotify.scio.bigquery.types.BigQueryType
import org.joda.time.LocalDate

object Professional {
  @BigQueryType.toTable
  case class ParsedProfessional(
    CLAIM_NUM: String,
    LINE_NUM: Option[String],
    MEM_ID: String,
    FORM_TYPE: Option[String],
    _claim_line_status: Option[String],
    CLAIM_LINE_STATUS_REASON: Option[String],
    FROM_DATE: Option[LocalDate],
    TO_DATE: Option[LocalDate],
    REC_DATE: Option[LocalDate],
    ENTRY_DATE: Option[LocalDate],
    PAID_DATE: Option[LocalDate],
    CHK_NUM: Option[String],
    POS: Option[String],
    ICD_DIAG_01: Option[String],
    ICD10_OR_HIGHER: Option[Boolean],
    BILL_PROV_ID: Option[String],
    BILL_PROV_LOC: Option[String],
    REF_PROV_ID: Option[String],
    REV_PROV_LOC: Option[String],
    ACO_ID: Option[String],
    MED_HOME_ID: Option[String],
    BEN_CONTRACT_CD: Option[String],
    BEN_PKG_ID: Option[String],
    BEN_SEQUENCE: Option[String],
    LOB: Option[String],
    PROC_CODE: Option[String],
    CPT_MOD_1: Option[String],
    CPT_MOD_2: Option[String],
    SV_UNITS: Option[String],
    AMT_BILLED: Option[String],
    AMT_ALLOWED: Option[String],
    AMT_ALLOWED_STAT: Option[String],
    AMT_PAID: Option[String],
    AMT_HRA: Option[String],
    AMT_DEDUCT: Option[String],
    AMT_COINS: Option[String],
    AMT_COPAY: Option[String],
    AMT_COB: Option[String],
    AMT_WITHHOLD: Option[String],
    AMT_DISALLOWED: Option[String],
    AUTH_NO: Option[String],
    CLAIM_IN_NETWORK: Option[String],
    PAR_PROV_IND: Option[String],
    MAINT_DATE: Option[LocalDate],
    CAP_IND: Option[Boolean],
    MEDICARE_SEQUESTRATION_IND: Option[String],
    AMT_PRE_MEDICARE_SEQUESTRATION: Option[String],
    COB_IND: Option[Boolean],
    CHK_DATE: Option[LocalDate],
    OTHER_INS_IND: Option[String],
    REMITT_NUM: Option[String],
    PAYMENT_STATUS: Option[String],
  )
}
