
# computed fields sources

version: 2

sources:

  - name: computed_fields
    description: Computed fields dataset
    database: cityblock-data
    schema: computed_fields

    tables:
      - name: results
      - name: latest_results

  - name: computed_reference
    description: Computed fields metadata
    database: cityblock-analytics
    schema: src_computed_reference

    tables:
      - name: src_computed_status