version: 2

models:
  - name: abs_procedures
    description: Collection of procedures from claims (facility and professional), EHR problems and encounters, and HIE events
    columns:
      - name: id
        description: Non-unique identifier based on `sourceId`, `procedureCode`, `serviceDateFrom`, and `encounterType`
        tests:
          - not_null
