#!/bin/bash
#
# Script to handle configurations for the Data Analytics team
#
# Only handle oncall configurations at this time, see help in order to understand usage
#

set -eu -o pipefail

if [[ ! $(which jq) ]]; then
  echo "Please install jq: `brew install jq`"
  exit 1
fi

display_help () {
  cat <<EOF 1>&2
  Script to either get or set on-call information for Data Analytics team

  Usage: $0 oncall {get|set} {primary|secondary} {person}"

  Examples:
    for current on-call info, do:                          $0 oncall get
    for current on-call on level, do:                      $0 oncall get secondary
    for setting on-call, do (first name lowercase only):   $0 oncall set primary katie


  After setting the on-call information, go to Slack and run "/oncall data" to confirm the changes have been made
  successfully.

  For any other concerns, please reach out to Platform team for assistance. If you would like to make changes to
  this script, please do so and create a PR for it. When adding new team members to the on-call rotation, ensure the
  'names_map.json' file is updated.

EOF
  exit 0
}

if [[ $1 == "-h" ]]; then
  display_help
fi

command=$1
set_or_get=$2
resource=${3:-''}
replacement=${4:-''}

if [[ $command != 'oncall' ]]; then
  echo "[ERROR] Only support oncall command at this time."
  exit 1
fi

if [[ $set_or_get != 'get'  && $set_or_get != 'set' ]]; then
  echo "[ERROR] Only support 'get' or 'set' command at this time (was provided '$set_or_get')."
  exit 1
fi

if [[ $set_or_get == 'get' ]]; then
  if [[ -z $resource ]]; then
    echo "Fetching all on-call information..."
    gsutil cat gs://cbh-analytics-configs/oncall/data.json | jq
    exit 0
  elif [[ $resource == 'primary' || $resource == 'secondary' ]]; then
    echo "Fetching all on-call information for $resource..."
    gsutil cat gs://cbh-analytics-configs/oncall/data.json | jq --arg resource "$resource" '.[$resource]'
    exit 0
  else
    echo "[ERROR] Only support 'primary' or 'secondary' (was provided '$resource')."
    exit 1
  fi
fi

validate_name () {
  full_name=$(cat names_map.json | jq --arg replacement "$replacement" '.[$replacement]' | tr -d '"')
  if [[ -z $full_name || $full_name == null ]]; then
    echo "[ERROR] Not able to find person: $replacement, see 'names_map.json' for available options."
    exit 1
  fi
}

if [[ $set_or_get == 'set' ]]; then
  if [[ -z $resource || -z $replacement ]]; then
    echo "[ERROR] Must specify level to set as well as person."
    exit 1
  elif [[ $resource == 'primary' || $resource == 'secondary' ]]; then
    validate_name
    echo "Going to set $resource as $full_name now..."
    gsutil cat gs://cbh-analytics-configs/oncall/data.json | jq \
     --arg resource "$resource" \
     --arg full_name "$full_name" \
     '.[$resource] = $full_name'  | \
     gsutil cp - gs://cbh-analytics-configs/oncall/data.json
    exit 0
  else
    echo "[ERROR] Only support 'primary' or 'secondary' (was provided '$resource')."
    exit 1
  fi
fi
