version: 2

models:
  - name:  all_suspects_ranked
    description: "\n
    Author: Caitlin Dugan\n
    Purpose: Combined list of suspect and persistent opportunities across all data sources, supplemented with new data weekly. Includes cf, ml, rb, models from lab, pharm, dx, cpt sources"

  - name: all_suspects_to_looker
    description: "\n
    Author: Caitlin Dugan\n
    Purpose: Combined and deduped list of suspect and persistent opportunities across all data sources, supplemented with new data weekly. Includes cf, ml, rb, models from lab, pharm, dx, cpt sources"

  - name: all_suspects_to_providers
    description: "\n
    Author: Caitlin Dugan\n
    Purpose: Combined and deduped list of suspect and persistent opportunities across all data sources, incuding only most recent data. Includes cf, ml, rb, models from lab, pharm, dx, cpt sources"

