
# all payer data sources

version: 2

sources:
  - name: elation_mirror
    description: Elation mirror source
    database: cbh-db-mirror-prod
    schema: elation_mirror

    tables:
      - name: visit_note_document_tag_latest
      - name: visit_note_latest
      - name: document_tag_latest
      - name: user_latest
      - name: appointment_latest
      - name: patient_immunization