version: 2

models:
  - name: agg_member_month_pharma
    description: "\n
    Authors: Gerardo Sierra\n
    Purpose: Aggregations of NDC and prescritons used at member month level. Including paid and allowed amounts as well"

  - name: agg_member_month_office_visits
    description: "\n
    Authors: Gerardo Sierra\n
    Purpose: Aggregations of Office visits by specialty group at the member month level"

