steps:
  - name: gcr.io/cloud-builders/docker
    id: health-events-svc-pull
    waitFor: ['-']
    entrypoint: /bin/bash
    args:
      - '-c'
      - |
        docker pull ${_HEALTH_EVENTS_SERVICE_IMAGE}:latest || exit 0

  - name: gcr.io/cloud-builders/docker
    id: health-events-svc-build
    waitFor: ['health-events-svc-pull']
    args:
      [
        'build',
        '--cache-from',
        '${_HEALTH_EVENTS_SERVICE_IMAGE}:latest',
        '-t',
        '${_HEALTH_EVENTS_SERVICE_IMAGE}:$SHORT_SHA',
        '-t',
        '${_HEALTH_EVENTS_SERVICE_IMAGE}:latest',
        '.',
      ]

  - name: gcr.io/cloud-builders/docker
    id: health-events-svc-push
    waitFor: ['health-events-svc-build']
    args: ['push', '${_HEALTH_EVENTS_SERVICE_IMAGE}']

  - name: 'node:14.15.1'
    id: install-node-dependencies
    entrypoint: npm
    args:
      - 'install'
    dir: ${_SERVICE_DIR}
    waitFor: ['-']

  - name: 'node:14.15.1'
    id: lint-service
    entrypoint: npm
    args: ['run', 'lint']
    waitFor: ['install-node-dependencies']
    dir: ${_SERVICE_DIR}

  - name: 'gcr.io/cloudsql-docker/gce-proxy:1.15'
    id: cloud-sql-proxy
    entrypoint: sh
    args:
      - '-c'
      - >-
        /cloud_sql_proxy -dir=/cloudsql -instances=${_CLOUD_SQL_INSTANCE} & while [ ! -f /cloudsql/stop ]; do sleep 2; done
    timeout: 600s
    waitFor: ['-']
    volumes:
      - name: 'db'
        path: '/cloudsql'
  
  - name: 'node:14.15.1'
    id: db-migrations
    entrypoint: 'sh'
    secretEnv: [DB_USER, DB_PASSWORD]
    args:
      - '-c'
      - >-
        export DB_USER=$$DB_USER && DB_PASSWORD=$$DB_PASSWORD && npm run migrate && touch /cloudsql/stop
    env:
      ['NODE_ENV=${_NODE_ENV}', 'DB_HOST=/cloudsql/${_CLOUD_SQL_INSTANCE}', 'DB_NAME=${_DB_NAME}']
    volumes:
      - name: 'db'
        path: '/cloudsql'
    dir: ${_SERVICE_DIR}
    waitFor: ['install-node-dependencies']

  - name: 'gcr.io/cloud-builders/gcloud'
    id: deploy-cloud-run
    waitFor: ['health-events-svc-push']
    entrypoint: 'bash'
    args:
      - '-c'
      - >-
        gcloud run deploy health-events-service-${_DEPLOY_ENV} --image=${_HEALTH_EVENTS_SERVICE_IMAGE}:latest --region=us-east1 --platform=managed --project=cbh-services-${_DEPLOY_ENV}

substitutions:
  _SERVICE_DIR: services/health_events_service
availableSecrets:
  secretManager:
    - versionName: 'projects/${_SECRETS_PROJECT}/secrets/${_DEPLOY_ENV}-health-events-service-db-user-name/versions/latest'
      env: DB_USER
    - versionName: 'projects/${_SECRETS_PROJECT}/secrets/${_DEPLOY_ENV}-health-events-service-db-user-password/versions/latest'
      env: DB_PASSWORD
timeout: 1200s
logsBucket: gs://cbh-cloud-build-logs/build-${_DEPLOY_ENV}-health-events-service
