module "mrt_computed_dataset" {
  source     = "../src/resource/bigquery/dataset"
  dataset_id = "mrt_computed"
  project    = var.project_id
  labels = {
    data = "phi"
  }
  special_group_access = [
    { special_group = "projectWriters", role = "WRITER" },
    { special_group = "projectOwners", role = "OWNER" },
    { special_group = "projectReaders", role = "READER" }
  ]
  user_access = [
    {
      email = "dataflow-job-runner@cityblock-data.iam.gserviceaccount.com",
      role  = "READER"
    }, # for k8s cronjobs in scio-jobs/k8s
    { email = "97093835752-compute@developer.gserviceaccount.com", role = "READER"}
  ]
  description = <<EOF
Destination for computed-field results generated by dbt.
EOF
}

module "medical_economics" {
  source     = "../src/resource/bigquery/dataset"
  project    = var.project_id
  dataset_id = "medical_economics"
  labels = {
    data = "phi"
  }
  special_group_access = [
    { special_group = "projectWriters", role = "WRITER" },
    { special_group = "projectOwners", role = "OWNER" },
    { special_group = "projectReaders", role = "READER" }
  ]
  user_access = [
    { email = module.dnah_jobs_svc_acct.email, role = "WRITER" }
  ]
}
