version: 2
models:
 - name: ftr_facility_costs_categories
   columns: 
    - name: claimId
      tests: 
        - not_null:
            severity: error

 - name: ftr_facility_stays
   columns: 
    - name: claimId
      tests: 
        - unique:
           severity: error

 - name: ftr_professional_costs_categories
   tests:
    - unique:
       column_name: "concat(claimId,lineId)"
