version: 2

models:
  - name: mrt_delivery_model_inputs
    description: Gather and prepare inputs for delivery model algorithm
    columns:
      - name: patientId
        tests:
          - unique
          - not_null
      - name: marketName
        description: >
          Member's home market; delivery model algorithm currently limited to
          non-disenrolled members in New York City, Connecticut, Massachusetts, CareFirst DC, and North Carolina markets
        tests:
          - not_null
          - accepted_values:
              values: ['New York City', 'Connecticut','Massachusetts','CareFirst DC','North Carolina']
      - name: topTwoHccsIncludeDementia
        tests:
          - not_null
      - name: topTwoHccsIncludeDialysis
        tests:
          - not_null
      - name: topTwoHccsIncludeParkinsonsOrHuntingtons
        tests:
          - not_null
      - name: topTwoHccsIncludeQuadraplegiaOrParaplegiaOrAmputationOrHemiplegia
        tests:
          - not_null
      - name: pathwayFieldIndicatesDialysis
        tests:
          - not_null
      - name: hasEvidenceOfAdvancedIllness
        tests:
          - not_null
      - name: hasEvidenceOfCcm
        tests:
          - not_null
      - name: hasZeroMedicalCostInPriorYearOrNoClaimsHistory
        description: Member has $0 in medical claims or no claim history in prior year
        tests:
          - not_null
      - name: chronicConditionCount
        tests:
          - not_null
      - name: ndcCount
        tests:
          - not_null
      - name: cotivitiLikelihoodOfHospitalizationInNextSixMonths
        description: Cotiviti prediction of the likelihood of being hospitalized in the next 6 months
        tests:
          - not_null
      - name: dialysisPaidDollarsPerMonth
        tests:
          - not_null
      - name: medicalPaidDollarsPerMonth
        tests:
          - not_null
      - name: snfPaidDollarsPerMonth
        tests:
          - not_null
      - name: dmePaidDollarsPerMonth
        tests:
          - not_null
      - name: bhPaidDollarsPerMonth
        tests:
          - not_null
      - name: rollingTwelveMonthEdVisitCount
        tests:
          - not_null
      - name: annualEdVisitCountYear1
        tests:
          - not_null
      - name: annualEdVisitCountYear2
        tests:
          - not_null
      - name: annualEdVisitCountYear3
        tests:
          - not_null
      - name: rollingTwelveMonthAcsEdVisitCount
        tests:
          - not_null
      - name: annualInpatientAdmitCountYear1
        tests:
          - not_null
      - name: annualInpatientAdmitCountYear2
        tests:
          - not_null
      - name: annualInpatientAdmitCountYear3
        tests:
          - not_null
      - name: rollingTwelveMonthUnplannedInpatientAdmitCount
        tests:
          - not_null
      - name: rollingTwelveMonthAcsInpatientCount
        tests:
          - not_null
      - name: rollingTwelveMonthReadmissionCount
        tests:
          - not_null
      - name: planPaidDollarsPerMemberMonthYear1
        tests:
          - not_null
      - name: planPaidDollarsPerMemberMonthYear2
        tests:
          - not_null
      - name: planPaidDollarsPerMemberMonthYear3
        tests:
          - not_null

  - name: mrt_delivery_model_flags
    description: Adds flags based on dialysis and three-year trend inputs
    columns:
      - name: patientId
        tests:
          - unique
          - not_null
      - name: hasEvidenceOfDialysis
        tests:
          - not_null
      - name: hasEvidenceOfCcm
        tests:
          - not_null
      - name: hasPositiveThreeYearPlanPaidDollarsPerMemberMonthTrend
        tests:
          - not_null
      - name: hasPositiveThreeYearAnnualEdVisitCountTrend
        tests:
          - not_null
      - name: hasPositiveThreeYearAnnualInpatientAdmitCountTrend
        tests:
          - not_null

  - name: mrt_delivery_model_weighted_values
    description: Calculates weighted member values for each input field
    columns:
      - name: id
        description: Unique identifier based on `patientId` and `field`
        tests:
          - unique
          - not_null
      - name: patientId
        tests:
          - not_null
      - name: initialModelAssignment
        description: Member care delivery model based on initial screens
        tests:
          - not_null
          - accepted_values:
              values: ['community', 'virtualIntegratedCare']
      - name: field
        tests:
          - not_null
      - name: value
        tests:
          - not_null
      - name: avgPlusTwoStdDev
        description: By field, sum of average value and two standard deviations
        tests:
          - not_null
      - name: isGreaterThanTwoStdDev
        description: Indicates whether member value is more than two standard deviations above field average
        tests:
          - not_null
      - name: scaledValue
        description: >
          If `isGreaterThanTwoStdDev` is true, this value is set to 1.
          Otherwise, it is equal to `value` divided by `avgPlusTwoStdDev`.
        tests:
          - not_null:
              severity: warn
      - name: weightedValue
        description: Product of `scaledValue` and field weight
        tests:
          - not_null

  - name: mrt_delivery_model_assignments
    description: Final delivery model values by member
    columns:
      - name: patientId
        tests:
          - unique
          - not_null
      - name: deliveryModel
        tests:
          - not_null
          - accepted_values:
              values: ['community', 'virtualIntegratedCare']
      - name: totalWeightedValue
        description: Sum of scaled and weighted member values for scored inputs
        tests:
          - not_null
