
version: 2

models:
  - name: abs_facility_multimarket
    description: Joins flattened facility claims with cost and use features
    tests:
      - unique:
          column_name: "concat(claimId, lineNumber)"
          severity: warn
    columns:
      - name: patientId
        tests:
          - dbt_utils.not_null_where:
              where: "partner != 'tufts' "

  - name: abs_pharmacy_multimarket
    description: Joins flattened pharmacy claims with cost and use features
    tests:
      - unique:
          column_name: "concat(claimId, lineId)"
    columns:
      - name: patientId
        tests:
          - dbt_utils.not_null_where:
              where: "partner != 'tufts' "

  - name: abs_professional_multimarket
    description: Joins flattened professional claims with cost and use features
    tests:
      - unique:
          column_name: "concat(claimId, lineId)"
          severity: warn
    columns:
      - name: patientId
        tests:
          - dbt_utils.not_null_where:
              where: "partner != 'tufts' "
