
version: 2

models:

  - name: ftr_pcp_attribution
    description: >
      VERSION: 0.4.0
      AUTHOR: dax@cityblock.com,nathan.matare@cityblock.com
      PURPOSE:
        Claims-based attribution of primary care physician for members with qualifying professional claims, that 
        distinguishes between CB and non-CB providers, and whether or not they are primary care or specialty providers
      PRD link: https://docs.google.com/document/d/1zx0QgDoyd8XpsOXkI-AFbb9jt2kNk7BNNLQqfbchTKA/edit#

    columns:
      - name: patientId
        tests:
          - unique

      - name: providerSurrogateId
        description: Provider surrogate ID; Extra information that does not correspond to attributedPcp assignment

      - name: partnerProviderId
        description: Partner-provided provider ID; Extra information that does not correspond to attributedPcp assignment

      - name: providerBillingId
        description: Associated billing provider ID; Billing providers are not necessarily the same as servicing providers; Extra information that does not correspond to attributedPcp assignment

      - name: providerServicingId
        description: Servicing provider of associated claims from which it was determined they were the attributedPcp based on our internal logic

      - name: providerServicingSpecialty
        description: Servicing provider specialty code

      - name: providerServicingSpecialtyDescription
        description: Servicing provider specialty code human-readable description

      - name: npi
        description: This may apply to attributedPcp/providerServicingId only in the case of Cityblock providers; Extra information that does not directly correspond to attributedPcp assignment

      - name: providerName
        description: Extra information that may offer some more context when populated

      - name: providerTaxonomyCode
        description: Extra information that may offer some more context when populated

      - name: providerTaxonomyTier
        description: Extra information that may offer some more context when populated

      - name: providerAffiliatedGroupName
        description: Extra information that may offer some more context when populated

      - name: cityblockProviderFlag
        description: Where cityblock provider 1, else 0 (or possibly null)

      - name: stringPrimarySpecialtyIndicator
        description: String indicators for whether a provider is a primary care provider, a specialty provider, or anything other than primary/specialty
        tests:
          - accepted_values:
              values: ['primary', 'specialty', 'other']

      - name: emVisitGroupedTotalInLookBack
        description: Grouped total count of E&M visits contained within the designated look back period, per line-associated servicing provider

      - name: lookBackDurationMonths
        description: Duration of the look back period in consideration for a respective run

      - name: lookBackDate
        description: The lower bound date of each respective look back period

      - name: attributedPcp
        description: If corresponding providerServicingId is an attributedPcp, then this column will contain one of the following values --> 'cbh primary', 'non-cbh primary', 'non-cbh specialist', 'cbh specialist'
        tests:
          - accepted_values:
              values: ['cbh primary', 'non-cbh primary', 'non-cbh specialist', 'cbh specialist']
