version: 2

sources:
  - name: care_management
    description: Member list for care management
    database: cityblock-analytics
    schema: src_care_management

    tables:
      - name: thpp_cm_mds_05142020
