
version: 2

models:
  - name: master_member_v1
    description: "\n
    Author: Andy Seiden\n
    Purpose: master member  table v1, based off cci and emblem silver claims member months and demographics files and  commons patient state. Serves as  central source of  truth about member eligibility information, and what we knew when. Concatenates eligibility information over time, and condenses to one row per member per  month, multiple rows where retro  changes occur in order to preserve historic info. Creates flags/scenarios when commons data mismatches with payer eligibility data, so care team can  do various actions to resolve or address conflicts. Meant to power looker dashboard and automated reports."

  - name: mrt_member_eligibility
    description: "\n
    Filtered version of `cityblock-analytics.mrt_member.master_member_v1`,
    identifying eligible member-months over the last three years\n
    "

  - name: mrt_member_eligibility_rolling_twelve_months
    description: Number of eligible months per member in a 3mo lagged rolling twelve month period
    columns:
      - name: patientId
        tests:
          - unique
          - not_null
      - name: memberMonths
        tests:
          - not_null

  - name: mrt_member_month_spine_cu_denom_all
    description: "\n
    Author: Andy Seiden\n
    Purpose: member-month format long table, one row per member per month of eligibility. includes some imputed/fake mm's as needed for operational functionality in looker. includes mm's where cityblock is both atrisk/responsible for the member, as well as those where we are not. includes some basic characteristics about the member e.g. cohort. used for pmpm denominators in looker claims self service"

  - name: mrt_member_month_spine_cu_denom
    description: "\n
    Author: Andy Seiden\n
    Purpose: same as the _all version of the table, except that it indludes ONLY the atRisk months for cityblock, where we are on the hook for the members claims or they are purely historic months of a pre-golive period. used mainly for downstream flags, computed fields, count of elig months for inputs to algos."
