module.exports = {
  production: {
    healthGorillaHost: "https://www.healthgorilla.com/",
    healthGorillaAudience: "logan.hasson",
    elationHost: "https://app.elationemr.com/api/2.0/",
    invalidMarketIds: [
      "3d8e4e1d-bdb5-4676-9e25-9b6fa248101f",
      "6a4df00d-6570-4f03-9d29-de01cc22b128",
    ],
    validEventTypes: [
      "vitals_saved",
      "reports_saved",
      "patients_saved",
      "vitals_deleted",
      "reports_deleted",
    ],
    validCCDSectionTypes: [
      "allergies",
      "demographics",
      "encounters",
      "functional_statuses",
      "immunizations",
      "medications",
      "results",
      "problems",
      "procedures",
      "social_history",
      "vitals",
      "reason_for_referral",
    ],
    secretsProjectName: "cbh-secrets",
    healthGorillaSecretName: "prod-healthgorilla-api-creds",
    elationSecretName: "prod-elation-api-creds",
  },
  test: {
    healthGorillaHost: "https://sandbox.healthgorilla.com/",
    healthGorillaAudience: "laurenfr",
    elationHost: "https://sandbox.elationemr.com/api/2.0/",
    invalidMarketIds: [
      "1bf5a200-cdb9-414d-9778-a584cd5bef8c",
      "ea2655eb-5411-4a76-bc63-89aa79a3f64c",
    ],
    validEventTypes: [
      "vitals_saved",
      "reports_saved",
      "patients_saved",
      "vitals_deleted",
      "reports_deleted",
    ],
    validCCDSectionTypes: [
      "allergies",
      "demographics",
      "encounters",
      "functional_statuses",
      "immunizations",
      "medications",
      "results",
      "problems",
      "procedures",
      "social_history",
      "vitals",
      "reason_for_referral",
    ],
    secretsProjectName: "cbh-secrets",
    healthGorillaSecretName: "dev-healthgorilla-api-creds",
    elationSecretName: "dev-elation-api-creds",
  },
};
