
version: 2

models:
  - name: mrt_claims_admit_coverage
    description: "
    Author:  Katie Claiborne\n
    Purpose: Flag member admit dates based on notification source
    "
    tests:
      - unique:
          column_name: "concat(patientId, admitDate, notificationSource)"
    columns:
      - name: patientId
      - name: admitDate
        description: 90-day lagged acute inpatient admissions occurring on or after CBH attribution
      - name: notificationSource
        tests:
          - accepted_values:
              values: ['hie alert', 'prior authorization']
          - not_null
      - name: hasNotification

  - name: mrt_claims_last_three_years_paid
    description: "\n
    Filtered version of `cityblock-analytics.mrt_self_service.mrt_claims_self_service`,\n
    limited to paid claims from the last three years\n
    "

  - name: mrt_claims_member_cost_classification_totals
    description: "\n
    Aggregation of `cityblock-analytics.mrt_self_service.mrt_claims_rolling_twelve_months`,\n
    summing paid amounts and counting admissions and emergency visits\n
    "

  - name: mrt_claims_monthly_costs_and_eligibility
    description: "\n
    Monthly totals of amount paid for claims by member and claimType (medical or pharmacy)."
    tests:
      - unique:
          column_name: "concat(patientId, monthFrom, yearFrom, claimType)"
    columns:
      - name: patientId
        tests:
          - not_null
      - name: monthFrom
      - name: yearFrom
      - name: yearSeq
      - name: isEligibleMonth
        tests:
          - accepted_values:
              values: [true, false]
              quote: false
      - name: claimType
        tests:
          - accepted_values:
              values: ['medical', 'pharmacy']
      - name: planPaidDollars

  - name: mrt_claims_pivoted_annual_encounters
    description: >
      Annual counts of emergency department visits and inpatient admissions by member,
      over last three full calendar years. `Year3` fields represent the most recent calendar year.
    columns:
      - name: patientId
        tests:
          - not_null
          - unique
      - name: annualEdVisitCountYear1
        tests:
          - not_null
      - name: annualEdVisitCountYear2
        tests:
          - not_null
      - name: annualEdVisitCountYear3
        tests:
          - not_null
      - name: annualInpatientAdmitCountYear1
        tests:
          - not_null
      - name: annualInpatientAdmitCountYear2
        tests:
          - not_null
      - name: annualInpatientAdmitCountYear3
        tests:
          - not_null

  - name: mrt_claims_pivoted_annual_medical_costs
    description: Annual plan-paid dollars per eligible month by member
    columns:
      - name: patientId
        tests:
          - not_null
          - unique
      - name: planPaidDollarsPerMemberMonthYear1
        tests:
          - not_null
      - name: planPaidDollarsPerMemberMonthYear2
        tests:
          - not_null
      - name: planPaidDollarsPerMemberMonthYear3
        tests:
          - not_null

  - name: mrt_claims_pivoted_cost_classification_totals
    description: Member paid amounts by cost category over rolling twelve-month period
    columns:
      - name: patientId
        tests:
          - not_null
          - unique
      - name: planPaidDollars
        description: Total paid amount for all claims
        tests:
          - not_null
      - name: medicalPaidDollars
        description: Total paid amount for medical claims
        tests:
          - not_null
      - name: rxPaidDollars
        description: Total paid amount for pharmacy claims
        tests:
          - not_null
      - name: rxPaidDollarsPercent
        description: Pharmacy paid amount as a percentage of total paid amount, with values ranging from zero to one

  - name: mrt_claims_rolling_twelve_months
    description: "\n
    Filtered version of `cityblock-analytics.mrt_self_service.mrt_claims_last_three_years_paid`,\n
    limited to claims from a rolling twelve-month period\n
    "

  - name: mrt_claims_self_service
    description: Normalized claims experience of Cityblock members across all partners. Supports downstream models, exports, computed fields, etc. Was previoulsy used for self-service analytics in looker before we added the _all model.
    tests:
      - not_null:
          column_name: patientId

  - name: mrt_claims_self_service_all
    description: Normalized claims experience of Cityblock members across all partners, including deidentified claims where the member identity is unknown. Is currently used for self-service analytics in looker. Does NOT support downstream models, exports, or computed fields, etc
    tests:
      - unique:
          column_name: "concat(claimId, lineNumber, claimLineStatus)"
          severity: warn
    columns:
      - name: claimType
      - name: formType
        description: professional (CMS-1500), facility (UB-04) or pharmacy
      - name: partner
      - name: partnerSourceName
      - name: claimId
        description: Global identifier within all payers' claims (internal)
      - name: partnerClaimId
      - name: lineNumber
        description: Claim line number for a single service
      - name: lineId
      - name: procedureCode
      - name: revenueCode
        description: Standard revenue code (only on facility claims and at the line-level)
      - name: partnerMemberId
      - name: commonId
      - name: patientId
      - name: providerServicingId
      - name: providerServicingSpecialty
      - name: providerBillingId
      - name: billType
        description: Facility claims only. Standard bill type providing information about the servicing provider
      - name: placeOfService
        description: Professional claims only. Standard place of service code
      - name: dateFrom
        description: Service start date
      - name: dateTo
        description: Service end date
      - name: dateAdmit
        description: Facility claims only. Date of admission to facility
      - name: dateDischarge
        description: Facility claims only. Date of discharge from facility
      - name: dischargeStatus
        description: Facility claims only. Standard discharge status code
      - name: amountAllowed
        description: The negotiated amount the provider receives (planPaid + copay + deductible + coinsurance + COB). Includes all denied claim lines.  For capitated claims provide FFS equivalent if available.
      - name: amountPlanPaid
        description: The amount for which the payer is responsible
      - name: principalProcedureCode
        description: Facility inpatient claims only. ICD-PCS
      - name: principalDiagnosisCode
        description: The principal diagnosis or first-listed diagnosis. ICD-CM
      - name: surrogateId
      - name: ndc
        description: National Drug Code, only for Rx claims
      - name: daysSupply
        description: Number of days the Rx claim supplies. Can be negative for adjustments.
      - name: brandIndicator
      - name: outpatientLocation
      - name: claimCategory
      - name: serviceCategory
      - name: serviceSubCategory
      - name: costCategory
        description: Cost Category as defined by Cost & Use
      - name: costSubCategory
        description: Cost Sub-Category as defined by Cost & Use
      - name: costSubCategoryDetail
        description: Cost Sub-Category Detail as defined by Cost & Use
      - name: costCategoryLine
      - name: costSubCategoryLine
      - name: costSubCategoryDetailLine
      - name: acuteInpatientCategoryFlag
        description: Acute inpatient flag - top in hierarchy
      - name: edCategoryFlag
        description: Non-admitted ED flag - claim doesn't contain an Acute Inpatient admission
      - name: obsCategoryFlag
        description: Observation without ED or Inaptient admit
      - name: readmissionFlag
        description: Inpatient admission that occurred within 30 days of the member's last inpatient admission, and was not a transfer/continuation of that last admission.
      - name: resultsInReadmissionFlag
        description: An inpatient admission that is followed within 30 days or less by a subsequent readmission of the same member, excluding transfers.
      - name: edServiceFlag
        description: Claim has an ED revenue code. Necessarily True for every ED flag. Potentially true for Acute Inpatient transfers or SNF claims.
      - name: icuServiceFlag
        description: Claim has an ICU revenue code.Potentially true for Acute Inpatient
      - name: stayType
      - name: stayGroup
      - name: patientDate
      - name: surgical
      - name: drgCode
      - name: drgCodeset
      - name: unplanned_admission
      - name: providerCategory
      - name: primaryCareProviderFlag
        description: Provider speciality code is primary care
      - name: surgicalProviderFlag
        description: Provider speciality code maps to a surgical provider
      - name: specialistProviderFlag
        description: Provider speciality code maps to a specialist provider
      - name: behavioralHealthProviderFlag
        description: Provider speciality code maps to a behavioral health provider
      - name: acsInpatientFlag
        description: Ambulatory Care Sensitive Inpatient Claim (University of Manitoba) 
      - name: acsInpatientTypes
        description: Type of Ambulatory Care Sensitive Inpatient Condition (University of Manitoba)
      - name: acsEdFlag
        description: Potentally Avoidable ED Claim (NYU Algorithm)
      - name: maxDateFrom
        description: The final service from date of all partner claims. To exclude bias from lag of claims receipt exclude the final 2-3 months
      - name: capitatedParty
      - name: capitatedFlag
        description: Capitation flag for a given service. There are many cases where we do not know whether a claim is capitated or not, represented by null values
      - name: costBucketMajor
        description: Cost & Use Bucket, Major, for TCOC
      - name: costBucketMinor
        description: Cost & Use Bucket, Minor, for TCOC
      - name: costClassification1
      - name: costClassification2
      - name: claimLineStatus
        description: Payment status of the claim line. Encounter means a claim from a capitated contract
        tests:
          - accepted_values:
              values: [Adjusted, Denied, Encounter, Open, Paid, Reissue, Unknown, Voided]
              severity: warn
      - name: finalClassification
      - name: lineOfBusiness
        description: Primary line of business as indicated on the claim (Commercial, Medicaid, Medicare)
      - name: subLineOfBusiness
        description: Secondary line of business as indicated on the claim (Fully Insured, Exchange, Medicare Advantage, Medicaid, HARP, DSNP)
      - name: providerServicingName
      - name: providerBillingName
      - name: admissionId
        description: Facility inpatient claims only. Identifier grouping multiple claims relating to a single admission
      - name: lengthOfStay 
      - name: procedureDescription 
      - name: revenueDescription 
      - name: principalProcedureDescription
      - name: providerServicingSpecialtyDescription
      - name: principalDiagnosisDescription
      - name: placeOfServiceDescription
      - name: billTypeDescription
      - name: dischargeStatusDescription 
      - name: dateOfBirth
        description: Date of birth according to the payer
      - name: dateOfDeath
        description: Date of death according to the payer. Known to be sparse - contains false negatives. Be warned!
