
version: 2

models:
  - name: src_care_pathway_input_fields
    description: Lists slugs and levels for all fields used in pathways
    columns:
      - name: id
        description: Unique identifier, based on `pathwaySlug`, `fieldSlug`, and `fieldLevel`
        tests:
          - unique
          - not_null
      - name: pathwaySlug
        description: Pathway in which field is used
      - name: fieldSlug
        description: Computed field used as pathway or pathway input
        tests:
          - not_null
      - name: fieldLevel
        description: >
          Relationship of field to pathway. A value of 0 indicates that the field is used as a pathway,
          1 indicates that the field is a direct input to the pathway, and so on.
        tests:
          - not_null
          - accepted_values:
              values: [0, 1, 2, 3, 4]
              quote: false
