
version: 2

models:
  - name: abs_ehr_note_encounters
    description: Flattens EHR encounter notes for classification as tends, connections, and face-to-face visits
    columns:
    - name: patientId
    - name: encounterSource
      tests:
        - accepted_values:
            values: ['acpny', 'elation']
    - name: encounterId
      tests:
        - unique
    - name: encounterIdType
    - name: encounterType
      description: Subcategory describing encounter modality / setting (Telemedicine, Office Visit, etc)
    - name: encounterDateTime
    - name: userId
      tests:
        - not_null
    - name: locationName
    - name: encounterNotes
    - name: isClinicalIntakeEncounter
      description: >
        In our New York market, clinical intakes are defined by Epic encounter characteristics.
        Specifically, encounters must meet two criteria:
        - `reason` contains `'%Clinical Intake%'`
        - `type` does not contain `'Telephon%'`
      tests:
        - accepted_values:
            values: [true, false]
            quote: false
        - not_null

  - name: abs_ehr_note_interactions
    description: >
      Add `isAssociatedWithClinicalIntake` flag and `clinicalIntakeId`.
      For our New York market, these fields are defined by Epic encounter characteristics.
      For our other markets, these fields are defined by Elation appointment and encounter characteristics,
      which are combined based on member, care team member, and date.
    columns:
      - name: encounterId
        tests:
          - unique
      - name: isAssociatedWithClinicalIntake
        tests:
          - not_null
      - name: clinicalIntakeId

  - name: abs_encounters
    columns:
      - name: id
        tests:
          - unique
          - not_null
