version: 2

models:
  - name: computed_field_results
    description: "\n
    Author: Katie Claiborne\n
    Purpose: Compile computed field results over time, appending new and updated values nightly."

  - name: latest_computed_field_results
    description: "\n
    Author: Katie Claiborne\n
    Purpose: Identify most recent result by member and computed field, create surrogate key for snapshot"

  - name: latest_computed_field_results_wide
    description: "Pivot results for all active fields"
    tests:
      - unique:
          column_name: patientId
