version: 2

models:
  - name: src_loinc_table_core
    description: Converts column names to camel case and adds two alternate identifier columns
    columns:
      - name: loincNumber
        description: '{{ doc("loinc__loinc_num") }}'
        tests:
          - not_null
          - unique
      - name: longCommonName
        description: '{{ doc("loinc__long_common_name") }}'
        tests:
          - not_null
      - name: loincNumberAltId1
        description: Five numeric characters preceding hyphen in LOINC term
        tests:
          - not_null
      - name: loincNumberAltId2
        description: Six numeric characters in LOINC term, with hyphen removed
        tests:
          - not_null
