version: 2

sources:
  - name: loinc
    database: reference-data-199919
    schema: loinc
    
    tables:
      - name: loinc_table_core
        description: Subset of fields describing LOINC (Logical Observation Identifier Names and Codes) terms
        columns:
          - name: LOINC_NUM
            description: '{{ doc("loinc__loinc_num") }}'
            tests:
              - not_null
              - unique
          - name: LONG_COMMON_NAME
            description: '{{ doc("loinc__long_common_name") }}'
            tests:
              - not_null
