
version: 2

models:
  - name: mrt_care_pathway_incremental_assignment_all
    description: Record of all pathway assignments and rankings, with creation timestamps
    columns:
      - name: assignmentId
        tests:
          - not_null
          - unique
      - name: patientId
        tests:
          - not_null
      - name: pathwaySlug
        tests:
          - not_null
      - name: memberPathwayRank
        tests:
          - not_null
      - name: createdAt
        tests:
          - not_null
