package cityblock.models.emblem_connecticare.silver

import com.spotify.scio.bigquery.types.BigQueryType
import org.joda.time.LocalDate

object Provider {
  @BigQueryType.toTable
  case class ParsedProvider(
    FACETS_PRPR_ID: String,
    PRVD_MDM_ID: Option[String],
    EFFV_DT: Option[LocalDate],
    TERM_DT: Option[LocalDate],
    TIN: Option[String],
    PROVIDERDEA: Option[String],
    NATL_PRVD_ID: Option[String],
    PROVIDERMEDICAIDLICENSE: Option[String],
    PROVIDERSTATELICENSE: Option[String],
    TYP_CD: Option[String],
    TYP_CD_LBL: Option[String],
    ENTY_SUB_TYP_CD: Option[String],
    ENTY_SUB_TYP_CD_LBL: Option[String],
    ORG_TYP_CD: Option[String],
    ORG_TYP_CD_LBL: Option[String],
    TXNMY_CD: Option[String],
    TXNMY_DESC: Option[String],
    PRV_STATUS_CD: Option[String],
    PRV_STATUS_CD_LBL: Option[String],
    LOCN_STAT_CD: Option[String],
    LOCN_STAT_CD_LBL: Option[String],
    FACY_TYP_CD: Option[String],
    FACY_TYP_CD_LBL: Option[String],
    LST_NM: Option[String],
    FRST_NM: Option[String],
    MIDL_NM: Option[String],
    GNDR_CD: Option[String],
    GNDR_CD_LBL: Option[String],
    BRTH_DT: Option[LocalDate],
    TTL: Option[String],
    TTL_CD_LBL: Option[String],
    PRIMARY_SPECIALTY_CODE: Option[String],
    PRIMARY_SPECIALTY_LABEL: Option[String],
    SECONDARY_SPECIALTY_CODE: Option[String],
    SECONDARY_SPECIALTY_LABEL: Option[String],
    TERTIERY_SPECIALTY_CODE: Option[String],
    TERTIERY_SPECIALTY_LABEL: Option[String],
    SVC_ADR_LN_1: Option[String],
    SVC_ADR_LN_2: Option[String],
    SVC_CITY: Option[String],
    SVC_ST_CD: Option[String],
    SVC_ST_CD_LBL: Option[String],
    SVC_CNTY: Option[String],
    SVC_ZIP_CD: Option[String],
    SVC_CTRY_CD: Option[String],
    SVC_CTRY_CD_LBL: Option[String],
    SVC_PRIM_WRK_PHON_NBR: Option[String],
    SVC_PRIM_WRK_PHON_EXTN_NBR: Option[String],
    SVC_FAX_NBR: Option[String],
    TAX_NM: Option[String],
    TAX_EFFV_DT: Option[LocalDate],
    TAX_TERM_DT: Option[LocalDate],
    BILLING_ADR_LN_1: Option[String],
    BILLING_ADR_LN_2: Option[String],
    BILLING_ADR_CITY: Option[String],
    BILLING_ST_CD: Option[String],
    BILLING_ST_CD_LBL: Option[String],
    BILLING_CNTY: Option[String],
    BILLING_CTRY_CD: Option[String],
    BILLING_CTRY_CD_LBL: Option[String],
    BILLING_PHON_NBR: Option[String],
    LANG_CD: Option[String],
    LANG_CD_LBL: Option[String]
  )
}
