
version: 2

models:

  - name: mrt_member_surveys
    description: "Processed results from survey responses"
    columns:
      - name: questionType
        description: Descriptive types converted from Q-Reviews codes
        tests:
          - not_null
      - name: npsScore
        description: Answer field corresponding to 'Net Promoter Score (0-10)' questionType value
