version: 2

models:
  - name: mrt_elation_problem_list
    description: "title: Problem list for Cityblock members, updated with diagnoses info for members as new cohorts become added |
    author: caitlin dugan |
    runtime: daily"

  - name: mrt_elation_provider_code_decision
    description: "title: Provider responses to HCC opportunities surfaced in Elation |
    author: caitlin dugan |
    runtime: daily"

  - name: mrt_elation_clinical_reminder_risk
    description: "title: Risk-related opportunities and gaps to Elation |
    author: caitlin dugan |
    runtime: daily"

  - name: mrt_elation_clinical_reminder_quality
    description: "title: Quality file for HCC and CDPS gaps to Elation |
    author: caitlin dugan |
    runtime: daily"

  - name: mrt_elation_clinical_reminder_rules
    description: "title: Rules file for HCC and CDPS gaps to Elation |
    author: caitlin dugan |
    runtime: daily"