package cityblock.models.emblem.silver

import com.spotify.scio.bigquery.types.BigQueryType
import org.joda.time.LocalDate

object PriorAuthorization {
  @BigQueryType.toTable
  case class ParsedPriorAuthorization(
    CaseNumber: Option[String],
    Pt_ID: String,
    Pt_First_Name: Option[String],
    Pt_Last_Name: Option[String],
    Age: Option[String],
    DOB: Option[String],
    LOB_Product: Option[String],
    LOB_Category: Option[String],
    LOB_Detail: Option[String],
    Client_ID: Option[String],
    Client_Name: Option[String],
    Plan_ID: Option[String],
    Grp_Num: Option[String],
    PCP_NPI: Option[String],
    PCP_Name: Option[String],
    Program_Code: Option[String],
    Program_Desc: Option[String],
    Program_Begin_Dt: Option[String],
    Program_End_Dt: Option[String],
    CM_Case_Manager: Option[String],
    Fac_NPI: Option[String],
    Fac_Name: Option[String],
    Fac_Address: Option[String],
    Fac_City: Option[String],
    Fac_State: Option[String],
    Fac_Zip: Option[String],
    Fac_Phone: Option[String],
    DX_Code_DX_Desc: Option[String],
    Treating_Prov_NPI: Option[String],
    Treating_Prov_Name: Option[String],
    Med_Grp_ID: Option[String],
    Med_Grp_Name: Option[String],
    PAR_or_Non_PAR: Option[String],
    Case_Type: Option[String],
    Care_Type: Option[String],
    Case_Source: Option[String],
    Delegate_System: Option[String],
    Case_Age: Option[String],
    Case_Status: Option[String],
    Case_Priority: Option[String],
    Stage: Option[String],
    Admit_Dt: Option[LocalDate],
    Disch_Dt: Option[LocalDate],
    App_Los: Option[String],
    Act_Los: Option[String],
    Variance: Option[String],
    Deny: Option[String],
    Pxc_Code: Option[String],
    Request_Recvd_Dt: Option[String],
    Request_Recvd_Time: Option[String],
    Place_of_Service: Option[String],
    Service_Type: Option[String],
    Service_Line_status: Option[String],
    Service_Status_Desc: Option[String],
    Service_Start_Dt: Option[String],
    Service_End_Dt: Option[String],
    Aprv_Units: Option[String],
    Deny_Units: Option[String],
    Unit_Type: Option[String],
    Inpt_or_Outpt: Option[String],
    Reason: Option[String],
    Create_Dt: Option[LocalDate],
    Created_By: Option[String],
    Last_Updated: Option[String],
    Last_Updated_By: Option[String],
    Business_Unit: Option[String],
  )
}
