
version: 2

models:
  - name: abs_care_pathway_dismissals
    description: Extracts dismissal elements from Commons `event` JSON string
    columns:
      - name: id
        tests:
          - unique
          - not_null
      - name: patientId
      - name: userId
      - name: pathwaySlug
      - name: reason
      - name: createdAt

  - name: abs_care_pathway_values
    description: "\n
    Author:  Katie Claiborne\n
    Purpose: Gather relevant computed field values and attach rank for active pathways by partner\n
    "
    tests:
      - unique:
          column_name: "concat(patientId, pathwaySlug)"
    columns:
      - name: patientId

      - name: partnerName
          - not_null
      - name: pathwaySlug
          - not_null
      - name: pathwayValue
        tests:
          - accepted_values:
              values: ['true', 'false']
          - not_null

      - name: partnerPathwayRank
        description: Populated only for active pathways in member market

  - name: hospice_program_flag
    description: Uses data from MMR files to create flags related to hospice eligibility
    columns:
      - name: patientID
          - not_null
      - name: payer
      - name: lineofbusiness
      - name: paymentYear
      - name: monthsHospPaymentYear
      - name: everHospice
      - name: currentHospice
      - name: maxHospicedate
      - name: minHospicedate
