version: 2

sources:
  - name: cotiviti
    description: Cotiviti model output tables
    database: cityblock-analytics
    schema: src_cotiviti

    tables:
      - name: appendix_expenditures
        description: Contains break-down and stats of expenditures by type (medical, pharmacy or both) for a model run
        columns:
          - name: expenditureType
          - name: minimumExpenditureDollars
          - name: maximumExpenditureDollars
          - name: averageExpenditureDollarsByMemberID
          - name: averageExpenditureDollarsByPersonYears
          - name: totalExpenditureDollars
          - name: totalNegativeExpendituresBreakOutDollars
          - name: basePeriodExpendituresEqualToZeroCount
          - name: basePeriodExpendituresGreaterThanZeroCount
          - name: basePeriodExpendituresLessThanZeroCount
          - name: runId
          - name: createdAt

      - name: appendix_general_run_info
        description: Contains record for each model run, including base period used in prediction
        columns:
          - name: runId
            tests:
              - unique:
                  severity: warn

      - name: appendix_prediction_summary
        description: Average values of risk scores for a given model run
        columns:
          - name: riskScoreType
          - name: modelName
          - name: modelId
          - name: riskScoreValue
          - name: isAgeGenderModel
            tests:
              - accepted_values:
                  values: [true, false]
                  quote: false
          - name: runId
          - name: createdAt

      - name: dxcg_clinical_classification_v7
        description: Google sheet with mappings between ACC, RCC, HCC and DxG codes with our own classification of how much these fall into buckets of physical, behavioral or social
        tests:
          - dbt_utils.expression_is_true:
              expression: "percentPhysical + percentBehavioral + percentSocial = 1.0"
        columns:
          - name: ACC_Seq
          - name: ACC_Label
          - name: RCC_Seq
          - name: RCC_Label
          - name: HCC_Seq
          - name: HCC_Label
          - name: DxG_Seq
          - name: DxG_Label
          - name: percentPhysical
            description: Fraction of this code that can be attributed to physical factors
          - name: percentBehavioral
            description: Fraction of this code that can be attributed to behavioral factors
          - name: percentSocial
            description: Fraction of this code that can be attributed to social factors

      - name: model_info
        description: General information about Cotiviti's models.
        columns:
          - name: modelId
            description: Cotiviti's model identifier
            tests:
              - unique
              - not_null
          - name: modelName
            tests:
              - not_null
          - name: bundle
          - name: predictionTime
            description: Indicates whether the predictions target a period during (concurrent) or after (prospective) the base period
            tests:
              - not_null
              - accepted_values:
                  values: ['concurrent', 'prospective']
          - name: predictionScoreType
            description: The model output can be a likelihood score between 0 and 1 or a relative risk score, which is a positive number
            tests:
              - not_null
              - accepted_values:
                  values: ['likelihood', 'risk']
          - name: predictionTargetEvent
            description: In case the model predictions have to do with an event, this field describes the type of event.
            tests:
              - accepted_values:
                  values: ['Inpatient Admission', 'Outpatient ED Visit', 'Readmission']
          - name: predictionTargetExpenditureType
            description: In case the model predictions have to do with annual expenditure, this field describes the expenditure types included.
            tests:
              - accepted_values:
                  values: ['Medical', 'Pharmacy', 'Medical + Pharmacy']
          - name: population
            description: Desciption of the population that the model was trained on, and is intended to make accurate predictions for.
            tests:
              - not_null
              - accepted_values:
                  values: ['commercial', 'medicare', 'medicaid']
          - name: expenditureCapDollars
            description: Some models cap annual expenditure during training, in order to mitigate the influence of outliers.
          - name: runOutPeriodMonths
            description: The recommended minimum number of months one should allow for late claims to be processed. This is used to determine the model base period.
            tests:
              - not_null
          - name: reports
            description: Cotiviti IDs of the reports that can be generated for this model
            tests:
              - not_null
          - name: isImplemented
            description: Whether the model outputs have been tested by us

      - name: output_member_data
        description: Contains member attributes at time of model run, including target population flag
        tests:
          - unique:
              column_name: "concat(patientId, runId)"

      - name: output_predictions
        description: Contains member score for each model run

      - name: output_risk_drivers_hcc
        description: Top-5 HCC scores contributing to a Cotiviti prediction, if available
        columns:
          - name: patientId
            tests:
              - not_null
          - name: modelId
            tests:
              - not_null
          - name: label
          - name: HCC
            description: HCC sequence or code, can be joined with HCC_Seq in `dxcg_clinical_classification_v7`
          - name: riskContributionPercent
            description: Percentage of the member's score that can be attributed to this HCC code
          - name: runId
            tests:
              - not_null
          - name: createdAt
            tests:
              - not_null

      - name: report_individual_risk_drivers
        description: Contains factors that drive the individual member's risk for a subset of members, for a subset of models
