version: 2

models:
  - name: health_home_tracking_report
    description: "title: health home tracking report segment records file |
    author: nabig chaudhry |
    runtime: daily"

  - name: health_home_cf_conditions
    description: "title: health home member computed field conditions |
    author: nabig chaudhry |
    runtime: daily"

  - name: health_home_asmt_conditions
    description: "title: health home member assessment conditions |
    author: nabig chaudhry |
    runtime: daily"

  - name: health_home_ny_billing_support
    description: "title: health home new york billing support upload file |
    author: nabig chaudhry |
    runtime: daily | notes: null values replaced with specific number of blank character spaces"

