
version: 2

models:
  - name: abs_medical_events
    description: "\n
    Author:  Katie Claiborne\n
    Purpose: Clean key fields and identify member state at time of receipt\n
    "
    columns:
      - name: patientVisitTypeEventId
        tests:
          - not_null
          - unique
      - name: patientVisitId
        description: Identifier based on `patientId` and `visitId`
        tests:
          - not_null
      - name: eventType
        description: Indicates whether event was 'Admit' or 'Discharge'
        tests:
          - accepted_values:
              values: ['Admit', 'Discharge']
          - not_null

  - name: abs_admit_discharge_events_combined
    description: "\n
    Author:  Katie Claiborne\n
    Purpose: Combine admit and discharge pings based on patientId, visitId, and visitType\n
    "
    columns:
      - name: hasPulmonaryDiagnosis
        description: Indicates whether visit included a diagnosis code beginning with J%, R05%, R06%, R09%, or R50%
        tests:
          - accepted_values:
              values: [true, false]
              quote: false
          - not_null
